# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .assume_stripe_installed_response import AssumeStripeInstalledResponse
    from .claim_stripe_sandbox_keys_response import ClaimStripeSandboxKeysResponse
    from .get_integration_webhook_url_response import GetIntegrationWebhookUrlResponse
    from .get_stripe_sandbox_claim_link_response import GetStripeSandboxClaimLinkResponse
    from .get_stripe_sandbox_keys_response import GetStripeSandboxKeysResponse
    from .install_integration_response import InstallIntegrationResponse
    from .install_stripe_claimable_sandbox_response import InstallStripeClaimableSandboxResponse
    from .install_stripe_response import InstallStripeResponse
    from .list_integrations_params import ListIntegrationsParams
    from .list_integrations_response import ListIntegrationsResponse
    from .list_stripe_sandbox_countries_response import ListStripeSandboxCountriesResponse
    from .load_sample_data_set_response import LoadSampleDataSetResponse
    from .run_integration_response import RunIntegrationResponse
    from .start_data_import_response import StartDataImportResponse
    from .uninstall_integration_response import UninstallIntegrationResponse
_dynamic_imports: typing.Dict[str, str] = {
    "AssumeStripeInstalledResponse": ".assume_stripe_installed_response",
    "ClaimStripeSandboxKeysResponse": ".claim_stripe_sandbox_keys_response",
    "GetIntegrationWebhookUrlResponse": ".get_integration_webhook_url_response",
    "GetStripeSandboxClaimLinkResponse": ".get_stripe_sandbox_claim_link_response",
    "GetStripeSandboxKeysResponse": ".get_stripe_sandbox_keys_response",
    "InstallIntegrationResponse": ".install_integration_response",
    "InstallStripeClaimableSandboxResponse": ".install_stripe_claimable_sandbox_response",
    "InstallStripeResponse": ".install_stripe_response",
    "ListIntegrationsParams": ".list_integrations_params",
    "ListIntegrationsResponse": ".list_integrations_response",
    "ListStripeSandboxCountriesResponse": ".list_stripe_sandbox_countries_response",
    "LoadSampleDataSetResponse": ".load_sample_data_set_response",
    "RunIntegrationResponse": ".run_integration_response",
    "StartDataImportResponse": ".start_data_import_response",
    "UninstallIntegrationResponse": ".uninstall_integration_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AssumeStripeInstalledResponse",
    "ClaimStripeSandboxKeysResponse",
    "GetIntegrationWebhookUrlResponse",
    "GetStripeSandboxClaimLinkResponse",
    "GetStripeSandboxKeysResponse",
    "InstallIntegrationResponse",
    "InstallStripeClaimableSandboxResponse",
    "InstallStripeResponse",
    "ListIntegrationsParams",
    "ListIntegrationsResponse",
    "ListStripeSandboxCountriesResponse",
    "LoadSampleDataSetResponse",
    "RunIntegrationResponse",
    "StartDataImportResponse",
    "UninstallIntegrationResponse",
]
