# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.integration_state import IntegrationState
from ...types.integration_type import IntegrationType


class ListIntegrationsParams(UniversalBaseModel):
    """
    Input parameters
    """

    billing_only: typing.Optional[bool] = None
    exclude_ids: typing.Optional[typing.List[str]] = None
    id: typing.Optional[str] = None
    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page limit (default 100)
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page offset (default 0)
    """

    state: typing.Optional[IntegrationState] = None
    type: typing.Optional[IntegrationType] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
