# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.feature_usage_time_series_response_data import FeatureUsageTimeSeriesResponseData
from .get_feature_usage_time_series_params import GetFeatureUsageTimeSeriesParams


class GetFeatureUsageTimeSeriesResponse(UniversalBaseModel):
    data: FeatureUsageTimeSeriesResponseData
    params: GetFeatureUsageTimeSeriesParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
