# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.time_series_granularity import TimeSeriesGranularity


class ListFeatureUsageHistoryParams(UniversalBaseModel):
    """
    Input parameters
    """

    company_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restrict to these company IDs; omit for every company in the environment
    """

    end_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Exclusive end of the window; must fall on an hour boundary
    """

    feature_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restrict to these event features; omit for every event feature in the environment. Where several features measure the same event, each is reported separately and a page may carry more rows than the requested limit
    """

    granularity: typing.Optional[TimeSeriesGranularity] = pydantic.Field(default=None)
    """
    Bucket the window; omit for a single total per company and feature
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page limit (default 100)
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page offset (default 0)
    """

    start_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Inclusive start of the window; must fall on an hour boundary
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
