# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.feature_usage_history_response_data import FeatureUsageHistoryResponseData
from .list_feature_usage_history_params import ListFeatureUsageHistoryParams


class ListFeatureUsageHistoryResponse(UniversalBaseModel):
    data: typing.List[FeatureUsageHistoryResponseData]
    params: ListFeatureUsageHistoryParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
