# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_catalog_response import CreateCatalogResponse
    from .delete_catalog_response import DeleteCatalogResponse
    from .get_catalog_response import GetCatalogResponse
    from .get_configuration_response import GetConfigurationResponse
    from .get_credit_bundles_in_catalog_response import GetCreditBundlesInCatalogResponse
    from .get_derived_features_response import GetDerivedFeaturesResponse
    from .get_plans_in_catalog_response import GetPlansInCatalogResponse
    from .list_catalogs_params import ListCatalogsParams
    from .list_catalogs_response import ListCatalogsResponse
    from .update_catalog_response import UpdateCatalogResponse
    from .update_configuration_response import UpdateConfigurationResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateCatalogResponse": ".create_catalog_response",
    "DeleteCatalogResponse": ".delete_catalog_response",
    "GetCatalogResponse": ".get_catalog_response",
    "GetConfigurationResponse": ".get_configuration_response",
    "GetCreditBundlesInCatalogResponse": ".get_credit_bundles_in_catalog_response",
    "GetDerivedFeaturesResponse": ".get_derived_features_response",
    "GetPlansInCatalogResponse": ".get_plans_in_catalog_response",
    "ListCatalogsParams": ".list_catalogs_params",
    "ListCatalogsResponse": ".list_catalogs_response",
    "UpdateCatalogResponse": ".update_catalog_response",
    "UpdateConfigurationResponse": ".update_configuration_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateCatalogResponse",
    "DeleteCatalogResponse",
    "GetCatalogResponse",
    "GetConfigurationResponse",
    "GetCreditBundlesInCatalogResponse",
    "GetDerivedFeaturesResponse",
    "GetPlansInCatalogResponse",
    "ListCatalogsParams",
    "ListCatalogsResponse",
    "UpdateCatalogResponse",
    "UpdateConfigurationResponse",
]
