# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .count_billing_product_match_companies_params import CountBillingProductMatchCompaniesParams
    from .count_billing_product_match_companies_response import CountBillingProductMatchCompaniesResponse
    from .count_plans_params import CountPlansParams
    from .count_plans_response import CountPlansResponse
    from .create_custom_plan_response import CreateCustomPlanResponse
    from .create_plan_response import CreatePlanResponse
    from .delete_plan_response import DeletePlanResponse
    from .delete_plan_version_params import DeletePlanVersionParams
    from .delete_plan_version_response import DeletePlanVersionResponse
    from .get_plan_params import GetPlanParams
    from .get_plan_response import GetPlanResponse
    from .list_billing_product_match_companies_params import ListBillingProductMatchCompaniesParams
    from .list_billing_product_match_companies_response import ListBillingProductMatchCompaniesResponse
    from .list_plan_issues_params import ListPlanIssuesParams
    from .list_plan_issues_response import ListPlanIssuesResponse
    from .list_plans_params import ListPlansParams
    from .list_plans_response import ListPlansResponse
    from .publish_plan_version_response import PublishPlanVersionResponse
    from .update_company_plans_response import UpdateCompanyPlansResponse
    from .update_plan_response import UpdatePlanResponse
    from .upsert_billing_product_plan_response import UpsertBillingProductPlanResponse
    from .upsert_plan_for_billing_product_response import UpsertPlanForBillingProductResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CountBillingProductMatchCompaniesParams": ".count_billing_product_match_companies_params",
    "CountBillingProductMatchCompaniesResponse": ".count_billing_product_match_companies_response",
    "CountPlansParams": ".count_plans_params",
    "CountPlansResponse": ".count_plans_response",
    "CreateCustomPlanResponse": ".create_custom_plan_response",
    "CreatePlanResponse": ".create_plan_response",
    "DeletePlanResponse": ".delete_plan_response",
    "DeletePlanVersionParams": ".delete_plan_version_params",
    "DeletePlanVersionResponse": ".delete_plan_version_response",
    "GetPlanParams": ".get_plan_params",
    "GetPlanResponse": ".get_plan_response",
    "ListBillingProductMatchCompaniesParams": ".list_billing_product_match_companies_params",
    "ListBillingProductMatchCompaniesResponse": ".list_billing_product_match_companies_response",
    "ListPlanIssuesParams": ".list_plan_issues_params",
    "ListPlanIssuesResponse": ".list_plan_issues_response",
    "ListPlansParams": ".list_plans_params",
    "ListPlansResponse": ".list_plans_response",
    "PublishPlanVersionResponse": ".publish_plan_version_response",
    "UpdateCompanyPlansResponse": ".update_company_plans_response",
    "UpdatePlanResponse": ".update_plan_response",
    "UpsertBillingProductPlanResponse": ".upsert_billing_product_plan_response",
    "UpsertPlanForBillingProductResponse": ".upsert_plan_for_billing_product_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CountBillingProductMatchCompaniesParams",
    "CountBillingProductMatchCompaniesResponse",
    "CountPlansParams",
    "CountPlansResponse",
    "CreateCustomPlanResponse",
    "CreatePlanResponse",
    "DeletePlanResponse",
    "DeletePlanVersionParams",
    "DeletePlanVersionResponse",
    "GetPlanParams",
    "GetPlanResponse",
    "ListBillingProductMatchCompaniesParams",
    "ListBillingProductMatchCompaniesResponse",
    "ListPlanIssuesParams",
    "ListPlanIssuesResponse",
    "ListPlansParams",
    "ListPlansResponse",
    "PublishPlanVersionResponse",
    "UpdateCompanyPlansResponse",
    "UpdatePlanResponse",
    "UpsertBillingProductPlanResponse",
    "UpsertPlanForBillingProductResponse",
]
