# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.custom_plan_billing_response_data import CustomPlanBillingResponseData
from .list_custom_plan_billings_params import ListCustomPlanBillingsParams


class ListCustomPlanBillingsResponse(UniversalBaseModel):
    data: typing.List[CustomPlanBillingResponseData]
    params: ListCustomPlanBillingsParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
