# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.custom_plan_billing_status import CustomPlanBillingStatus


class ListCustomPlanBillingsParams(UniversalBaseModel):
    """
    Input parameters
    """

    company_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter by company ID
    """

    limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page limit (default 100)
    """

    offset: typing.Optional[int] = pydantic.Field(default=None)
    """
    Page offset (default 0)
    """

    plan_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter by plan ID
    """

    status: typing.Optional[CustomPlanBillingStatus] = pydantic.Field(default=None)
    """
    Filter by billing status
    """

    statuses: typing.Optional[typing.List[CustomPlanBillingStatus]] = pydantic.Field(default=None)
    """
    Filter by multiple billing statuses
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
