# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.company_detail_response_data import CompanyDetailResponseData
from .list_billing_product_match_companies_params import ListBillingProductMatchCompaniesParams


class ListBillingProductMatchCompaniesResponse(UniversalBaseModel):
    data: typing.List[CompanyDetailResponseData]
    params: ListBillingProductMatchCompaniesParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
