# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError as core_api_error_ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.internal_server_error import InternalServerError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.api_error import ApiError as types_api_error_ApiError
from ..types.create_plan_request_body import CreatePlanRequestBody
from ..types.plan_bundle_credit_grant_request_body import PlanBundleCreditGrantRequestBody
from ..types.plan_bundle_entitlement_request_body import PlanBundleEntitlementRequestBody
from ..types.update_plan_request_body import UpdatePlanRequestBody
from ..types.update_plan_trait_trait_request_body import UpdatePlanTraitTraitRequestBody
from ..types.upsert_billing_product_request_body import UpsertBillingProductRequestBody
from .types.create_plan_bundle_response import CreatePlanBundleResponse
from .types.update_plan_bundle_response import UpdatePlanBundleResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawPlanbundleClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_plan_bundle(
        self,
        *,
        entitlements: typing.Sequence[PlanBundleEntitlementRequestBody],
        billing_product: typing.Optional[UpsertBillingProductRequestBody] = OMIT,
        credit_grants: typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]] = OMIT,
        plan: typing.Optional[CreatePlanRequestBody] = OMIT,
        traits: typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreatePlanBundleResponse]:
        """
        Parameters
        ----------
        entitlements : typing.Sequence[PlanBundleEntitlementRequestBody]

        billing_product : typing.Optional[UpsertBillingProductRequestBody]

        credit_grants : typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]]

        plan : typing.Optional[CreatePlanRequestBody]

        traits : typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreatePlanBundleResponse]
            Created
        """
        _response = self._client_wrapper.httpx_client.request(
            "plan-bundles",
            method="POST",
            json={
                "billing_product": convert_and_respect_annotation_metadata(
                    object_=billing_product, annotation=UpsertBillingProductRequestBody, direction="write"
                ),
                "credit_grants": convert_and_respect_annotation_metadata(
                    object_=credit_grants,
                    annotation=typing.Sequence[PlanBundleCreditGrantRequestBody],
                    direction="write",
                ),
                "entitlements": convert_and_respect_annotation_metadata(
                    object_=entitlements,
                    annotation=typing.Sequence[PlanBundleEntitlementRequestBody],
                    direction="write",
                ),
                "plan": convert_and_respect_annotation_metadata(
                    object_=plan, annotation=CreatePlanRequestBody, direction="write"
                ),
                "traits": convert_and_respect_annotation_metadata(
                    object_=traits, annotation=typing.Sequence[UpdatePlanTraitTraitRequestBody], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePlanBundleResponse,
                    parse_obj_as(
                        type_=CreatePlanBundleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )

    def update_plan_bundle(
        self,
        plan_bundle_id: str,
        *,
        entitlements: typing.Sequence[PlanBundleEntitlementRequestBody],
        billing_product: typing.Optional[UpsertBillingProductRequestBody] = OMIT,
        credit_grants: typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]] = OMIT,
        plan: typing.Optional[UpdatePlanRequestBody] = OMIT,
        traits: typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdatePlanBundleResponse]:
        """
        Parameters
        ----------
        plan_bundle_id : str
            plan_bundle_id

        entitlements : typing.Sequence[PlanBundleEntitlementRequestBody]

        billing_product : typing.Optional[UpsertBillingProductRequestBody]

        credit_grants : typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]]

        plan : typing.Optional[UpdatePlanRequestBody]

        traits : typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdatePlanBundleResponse]
            OK
        """
        _response = self._client_wrapper.httpx_client.request(
            f"plan-bundles/{jsonable_encoder(plan_bundle_id)}",
            method="PUT",
            json={
                "billing_product": convert_and_respect_annotation_metadata(
                    object_=billing_product, annotation=UpsertBillingProductRequestBody, direction="write"
                ),
                "credit_grants": convert_and_respect_annotation_metadata(
                    object_=credit_grants,
                    annotation=typing.Sequence[PlanBundleCreditGrantRequestBody],
                    direction="write",
                ),
                "entitlements": convert_and_respect_annotation_metadata(
                    object_=entitlements,
                    annotation=typing.Sequence[PlanBundleEntitlementRequestBody],
                    direction="write",
                ),
                "plan": convert_and_respect_annotation_metadata(
                    object_=plan, annotation=UpdatePlanRequestBody, direction="write"
                ),
                "traits": convert_and_respect_annotation_metadata(
                    object_=traits, annotation=typing.Sequence[UpdatePlanTraitTraitRequestBody], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePlanBundleResponse,
                    parse_obj_as(
                        type_=UpdatePlanBundleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )


class AsyncRawPlanbundleClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_plan_bundle(
        self,
        *,
        entitlements: typing.Sequence[PlanBundleEntitlementRequestBody],
        billing_product: typing.Optional[UpsertBillingProductRequestBody] = OMIT,
        credit_grants: typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]] = OMIT,
        plan: typing.Optional[CreatePlanRequestBody] = OMIT,
        traits: typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreatePlanBundleResponse]:
        """
        Parameters
        ----------
        entitlements : typing.Sequence[PlanBundleEntitlementRequestBody]

        billing_product : typing.Optional[UpsertBillingProductRequestBody]

        credit_grants : typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]]

        plan : typing.Optional[CreatePlanRequestBody]

        traits : typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreatePlanBundleResponse]
            Created
        """
        _response = await self._client_wrapper.httpx_client.request(
            "plan-bundles",
            method="POST",
            json={
                "billing_product": convert_and_respect_annotation_metadata(
                    object_=billing_product, annotation=UpsertBillingProductRequestBody, direction="write"
                ),
                "credit_grants": convert_and_respect_annotation_metadata(
                    object_=credit_grants,
                    annotation=typing.Sequence[PlanBundleCreditGrantRequestBody],
                    direction="write",
                ),
                "entitlements": convert_and_respect_annotation_metadata(
                    object_=entitlements,
                    annotation=typing.Sequence[PlanBundleEntitlementRequestBody],
                    direction="write",
                ),
                "plan": convert_and_respect_annotation_metadata(
                    object_=plan, annotation=CreatePlanRequestBody, direction="write"
                ),
                "traits": convert_and_respect_annotation_metadata(
                    object_=traits, annotation=typing.Sequence[UpdatePlanTraitTraitRequestBody], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreatePlanBundleResponse,
                    parse_obj_as(
                        type_=CreatePlanBundleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )

    async def update_plan_bundle(
        self,
        plan_bundle_id: str,
        *,
        entitlements: typing.Sequence[PlanBundleEntitlementRequestBody],
        billing_product: typing.Optional[UpsertBillingProductRequestBody] = OMIT,
        credit_grants: typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]] = OMIT,
        plan: typing.Optional[UpdatePlanRequestBody] = OMIT,
        traits: typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdatePlanBundleResponse]:
        """
        Parameters
        ----------
        plan_bundle_id : str
            plan_bundle_id

        entitlements : typing.Sequence[PlanBundleEntitlementRequestBody]

        billing_product : typing.Optional[UpsertBillingProductRequestBody]

        credit_grants : typing.Optional[typing.Sequence[PlanBundleCreditGrantRequestBody]]

        plan : typing.Optional[UpdatePlanRequestBody]

        traits : typing.Optional[typing.Sequence[UpdatePlanTraitTraitRequestBody]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdatePlanBundleResponse]
            OK
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"plan-bundles/{jsonable_encoder(plan_bundle_id)}",
            method="PUT",
            json={
                "billing_product": convert_and_respect_annotation_metadata(
                    object_=billing_product, annotation=UpsertBillingProductRequestBody, direction="write"
                ),
                "credit_grants": convert_and_respect_annotation_metadata(
                    object_=credit_grants,
                    annotation=typing.Sequence[PlanBundleCreditGrantRequestBody],
                    direction="write",
                ),
                "entitlements": convert_and_respect_annotation_metadata(
                    object_=entitlements,
                    annotation=typing.Sequence[PlanBundleEntitlementRequestBody],
                    direction="write",
                ),
                "plan": convert_and_respect_annotation_metadata(
                    object_=plan, annotation=UpdatePlanRequestBody, direction="write"
                ),
                "traits": convert_and_respect_annotation_metadata(
                    object_=traits, annotation=typing.Sequence[UpdatePlanTraitTraitRequestBody], direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdatePlanBundleResponse,
                    parse_obj_as(
                        type_=UpdatePlanBundleResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        types_api_error_ApiError,
                        parse_obj_as(
                            type_=types_api_error_ApiError,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise core_api_error_ApiError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.text
            )
        raise core_api_error_ApiError(
            status_code=_response.status_code, headers=dict(_response.headers), body=_response_json
        )
