# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.migration_error_code import MigrationErrorCode
from ..types.migration_proration_behavior import MigrationProrationBehavior
from ..types.plan_type import PlanType
from ..types.plan_version_company_migration_status import PlanVersionCompanyMigrationStatus
from ..types.plan_version_migration_status import PlanVersionMigrationStatus
from ..types.plan_version_migration_strategy import PlanVersionMigrationStrategy
from .raw_client import AsyncRawPlanmigrationsClient, RawPlanmigrationsClient
from .types.cancel_migration_response import CancelMigrationResponse
from .types.complete_migration_now_response import CompleteMigrationNowResponse
from .types.count_company_migrations_response import CountCompanyMigrationsResponse
from .types.count_migrations_response import CountMigrationsResponse
from .types.create_migration_response import CreateMigrationResponse
from .types.get_migration_response import GetMigrationResponse
from .types.list_company_migrations_response import ListCompanyMigrationsResponse
from .types.list_migrations_response import ListMigrationsResponse
from .types.preview_migration_response import PreviewMigrationResponse
from .types.retry_company_migration_response import RetryCompanyMigrationResponse
from .types.retry_migration_response import RetryMigrationResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PlanmigrationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPlanmigrationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPlanmigrationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPlanmigrationsClient
        """
        return self._raw_client

    def list_company_migrations(
        self,
        *,
        migration_id: str,
        q: typing.Optional[str] = None,
        status: typing.Optional[PlanVersionCompanyMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCompanyMigrationsResponse:
        """
        Parameters
        ----------
        migration_id : str

        q : typing.Optional[str]

        status : typing.Optional[PlanVersionCompanyMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCompanyMigrationsResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.list_company_migrations(
            migration_id="migration_id",
            q="q",
            status="cancelled",
            limit=1000000,
            offset=1000000,
        )
        """
        _response = self._raw_client.list_company_migrations(
            migration_id=migration_id, q=q, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def retry_company_migration(
        self, plan_version_company_migration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetryCompanyMigrationResponse:
        """
        Parameters
        ----------
        plan_version_company_migration_id : str
            plan_version_company_migration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetryCompanyMigrationResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.retry_company_migration(
            plan_version_company_migration_id="plan_version_company_migration_id",
        )
        """
        _response = self._raw_client.retry_company_migration(
            plan_version_company_migration_id, request_options=request_options
        )
        return _response.data

    def count_company_migrations(
        self,
        *,
        migration_id: str,
        q: typing.Optional[str] = None,
        status: typing.Optional[PlanVersionCompanyMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CountCompanyMigrationsResponse:
        """
        Parameters
        ----------
        migration_id : str

        q : typing.Optional[str]

        status : typing.Optional[PlanVersionCompanyMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CountCompanyMigrationsResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.count_company_migrations(
            migration_id="migration_id",
            q="q",
            status="cancelled",
            limit=1000000,
            offset=1000000,
        )
        """
        _response = self._raw_client.count_company_migrations(
            migration_id=migration_id, q=q, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def list_migrations(
        self,
        *,
        plan_version_id: str,
        status: typing.Optional[PlanVersionMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMigrationsResponse:
        """
        Parameters
        ----------
        plan_version_id : str

        status : typing.Optional[PlanVersionMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMigrationsResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.list_migrations(
            plan_version_id="plan_version_id",
            status="cancelled",
            limit=1000000,
            offset=1000000,
        )
        """
        _response = self._raw_client.list_migrations(
            plan_version_id=plan_version_id, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def create_migration(
        self,
        *,
        plan_id: str,
        plan_version_id_to: str,
        strategy: PlanVersionMigrationStrategy,
        target_plan_type: PlanType,
        company_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        excluded_company_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        plan_version_ids_from: typing.Optional[typing.Sequence[str]] = OMIT,
        proration_behavior: typing.Optional[MigrationProrationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMigrationResponse:
        """
        Parameters
        ----------
        plan_id : str

        plan_version_id_to : str

        strategy : PlanVersionMigrationStrategy

        target_plan_type : PlanType

        company_ids : typing.Optional[typing.Sequence[str]]

        excluded_company_ids : typing.Optional[typing.Sequence[str]]

        plan_version_ids_from : typing.Optional[typing.Sequence[str]]

        proration_behavior : typing.Optional[MigrationProrationBehavior]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMigrationResponse
            Created

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.create_migration(
            plan_id="plan_id",
            plan_version_id_to="plan_version_id_to",
            strategy="end_of_billing_period",
            target_plan_type="plan",
        )
        """
        _response = self._raw_client.create_migration(
            plan_id=plan_id,
            plan_version_id_to=plan_version_id_to,
            strategy=strategy,
            target_plan_type=target_plan_type,
            company_ids=company_ids,
            excluded_company_ids=excluded_company_ids,
            plan_version_ids_from=plan_version_ids_from,
            proration_behavior=proration_behavior,
            request_options=request_options,
        )
        return _response.data

    def get_migration(
        self, plan_version_migration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetMigrationResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMigrationResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.get_migration(
            plan_version_migration_id="plan_version_migration_id",
        )
        """
        _response = self._raw_client.get_migration(plan_version_migration_id, request_options=request_options)
        return _response.data

    def cancel_migration(
        self, plan_version_migration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelMigrationResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelMigrationResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.cancel_migration(
            plan_version_migration_id="plan_version_migration_id",
        )
        """
        _response = self._raw_client.cancel_migration(plan_version_migration_id, request_options=request_options)
        return _response.data

    def complete_migration_now(
        self,
        plan_version_migration_id: str,
        *,
        proration_behavior: typing.Optional[MigrationProrationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompleteMigrationNowResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        proration_behavior : typing.Optional[MigrationProrationBehavior]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompleteMigrationNowResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.complete_migration_now(
            plan_version_migration_id="plan_version_migration_id",
        )
        """
        _response = self._raw_client.complete_migration_now(
            plan_version_migration_id, proration_behavior=proration_behavior, request_options=request_options
        )
        return _response.data

    def retry_migration(
        self,
        plan_version_migration_id: str,
        *,
        error_codes: typing.Sequence[MigrationErrorCode],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetryMigrationResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        error_codes : typing.Sequence[MigrationErrorCode]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetryMigrationResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.retry_migration(
            plan_version_migration_id="plan_version_migration_id",
            error_codes=["ambiguous_subscription_item"],
        )
        """
        _response = self._raw_client.retry_migration(
            plan_version_migration_id, error_codes=error_codes, request_options=request_options
        )
        return _response.data

    def count_migrations(
        self,
        *,
        plan_version_id: str,
        status: typing.Optional[PlanVersionMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CountMigrationsResponse:
        """
        Parameters
        ----------
        plan_version_id : str

        status : typing.Optional[PlanVersionMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CountMigrationsResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.count_migrations(
            plan_version_id="plan_version_id",
            status="cancelled",
            limit=1000000,
            offset=1000000,
        )
        """
        _response = self._raw_client.count_migrations(
            plan_version_id=plan_version_id, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    def preview_migration(
        self,
        *,
        plan_id: str,
        plan_version_id_to: str,
        target_plan_type: PlanType,
        company_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        plan_version_ids_from: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreviewMigrationResponse:
        """
        Parameters
        ----------
        plan_id : str

        plan_version_id_to : str

        target_plan_type : PlanType

        company_ids : typing.Optional[typing.Sequence[str]]

        plan_version_ids_from : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreviewMigrationResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.planmigrations.preview_migration(
            plan_id="plan_id",
            plan_version_id_to="plan_version_id_to",
            target_plan_type="plan",
        )
        """
        _response = self._raw_client.preview_migration(
            plan_id=plan_id,
            plan_version_id_to=plan_version_id_to,
            target_plan_type=target_plan_type,
            company_ids=company_ids,
            plan_version_ids_from=plan_version_ids_from,
            request_options=request_options,
        )
        return _response.data


class AsyncPlanmigrationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPlanmigrationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPlanmigrationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPlanmigrationsClient
        """
        return self._raw_client

    async def list_company_migrations(
        self,
        *,
        migration_id: str,
        q: typing.Optional[str] = None,
        status: typing.Optional[PlanVersionCompanyMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCompanyMigrationsResponse:
        """
        Parameters
        ----------
        migration_id : str

        q : typing.Optional[str]

        status : typing.Optional[PlanVersionCompanyMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCompanyMigrationsResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.list_company_migrations(
                migration_id="migration_id",
                q="q",
                status="cancelled",
                limit=1000000,
                offset=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_company_migrations(
            migration_id=migration_id, q=q, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def retry_company_migration(
        self, plan_version_company_migration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetryCompanyMigrationResponse:
        """
        Parameters
        ----------
        plan_version_company_migration_id : str
            plan_version_company_migration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetryCompanyMigrationResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.retry_company_migration(
                plan_version_company_migration_id="plan_version_company_migration_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retry_company_migration(
            plan_version_company_migration_id, request_options=request_options
        )
        return _response.data

    async def count_company_migrations(
        self,
        *,
        migration_id: str,
        q: typing.Optional[str] = None,
        status: typing.Optional[PlanVersionCompanyMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CountCompanyMigrationsResponse:
        """
        Parameters
        ----------
        migration_id : str

        q : typing.Optional[str]

        status : typing.Optional[PlanVersionCompanyMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CountCompanyMigrationsResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.count_company_migrations(
                migration_id="migration_id",
                q="q",
                status="cancelled",
                limit=1000000,
                offset=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.count_company_migrations(
            migration_id=migration_id, q=q, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def list_migrations(
        self,
        *,
        plan_version_id: str,
        status: typing.Optional[PlanVersionMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListMigrationsResponse:
        """
        Parameters
        ----------
        plan_version_id : str

        status : typing.Optional[PlanVersionMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMigrationsResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.list_migrations(
                plan_version_id="plan_version_id",
                status="cancelled",
                limit=1000000,
                offset=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_migrations(
            plan_version_id=plan_version_id, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def create_migration(
        self,
        *,
        plan_id: str,
        plan_version_id_to: str,
        strategy: PlanVersionMigrationStrategy,
        target_plan_type: PlanType,
        company_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        excluded_company_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        plan_version_ids_from: typing.Optional[typing.Sequence[str]] = OMIT,
        proration_behavior: typing.Optional[MigrationProrationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMigrationResponse:
        """
        Parameters
        ----------
        plan_id : str

        plan_version_id_to : str

        strategy : PlanVersionMigrationStrategy

        target_plan_type : PlanType

        company_ids : typing.Optional[typing.Sequence[str]]

        excluded_company_ids : typing.Optional[typing.Sequence[str]]

        plan_version_ids_from : typing.Optional[typing.Sequence[str]]

        proration_behavior : typing.Optional[MigrationProrationBehavior]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMigrationResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.create_migration(
                plan_id="plan_id",
                plan_version_id_to="plan_version_id_to",
                strategy="end_of_billing_period",
                target_plan_type="plan",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_migration(
            plan_id=plan_id,
            plan_version_id_to=plan_version_id_to,
            strategy=strategy,
            target_plan_type=target_plan_type,
            company_ids=company_ids,
            excluded_company_ids=excluded_company_ids,
            plan_version_ids_from=plan_version_ids_from,
            proration_behavior=proration_behavior,
            request_options=request_options,
        )
        return _response.data

    async def get_migration(
        self, plan_version_migration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetMigrationResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetMigrationResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.get_migration(
                plan_version_migration_id="plan_version_migration_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_migration(plan_version_migration_id, request_options=request_options)
        return _response.data

    async def cancel_migration(
        self, plan_version_migration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelMigrationResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelMigrationResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.cancel_migration(
                plan_version_migration_id="plan_version_migration_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_migration(plan_version_migration_id, request_options=request_options)
        return _response.data

    async def complete_migration_now(
        self,
        plan_version_migration_id: str,
        *,
        proration_behavior: typing.Optional[MigrationProrationBehavior] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompleteMigrationNowResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        proration_behavior : typing.Optional[MigrationProrationBehavior]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompleteMigrationNowResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.complete_migration_now(
                plan_version_migration_id="plan_version_migration_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.complete_migration_now(
            plan_version_migration_id, proration_behavior=proration_behavior, request_options=request_options
        )
        return _response.data

    async def retry_migration(
        self,
        plan_version_migration_id: str,
        *,
        error_codes: typing.Sequence[MigrationErrorCode],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RetryMigrationResponse:
        """
        Parameters
        ----------
        plan_version_migration_id : str
            plan_version_migration_id

        error_codes : typing.Sequence[MigrationErrorCode]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetryMigrationResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.retry_migration(
                plan_version_migration_id="plan_version_migration_id",
                error_codes=["ambiguous_subscription_item"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retry_migration(
            plan_version_migration_id, error_codes=error_codes, request_options=request_options
        )
        return _response.data

    async def count_migrations(
        self,
        *,
        plan_version_id: str,
        status: typing.Optional[PlanVersionMigrationStatus] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CountMigrationsResponse:
        """
        Parameters
        ----------
        plan_version_id : str

        status : typing.Optional[PlanVersionMigrationStatus]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CountMigrationsResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.count_migrations(
                plan_version_id="plan_version_id",
                status="cancelled",
                limit=1000000,
                offset=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.count_migrations(
            plan_version_id=plan_version_id, status=status, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data

    async def preview_migration(
        self,
        *,
        plan_id: str,
        plan_version_id_to: str,
        target_plan_type: PlanType,
        company_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        plan_version_ids_from: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreviewMigrationResponse:
        """
        Parameters
        ----------
        plan_id : str

        plan_version_id_to : str

        target_plan_type : PlanType

        company_ids : typing.Optional[typing.Sequence[str]]

        plan_version_ids_from : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreviewMigrationResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.planmigrations.preview_migration(
                plan_id="plan_id",
                plan_version_id_to="plan_version_id_to",
                target_plan_type="plan",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preview_migration(
            plan_id=plan_id,
            plan_version_id_to=plan_version_id_to,
            target_plan_type=target_plan_type,
            company_ids=company_ids,
            plan_version_ids_from=plan_version_ids_from,
            request_options=request_options,
        )
        return _response.data
