# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.billing_collection_method import BillingCollectionMethod
from ..types.checkout_field_value import CheckoutFieldValue
from ..types.customer_billing_address import CustomerBillingAddress
from ..types.plan_selection import PlanSelection
from ..types.tax_id_input import TaxIdInput
from ..types.update_add_on_request_body import UpdateAddOnRequestBody
from ..types.update_auto_topup_override_request_body import UpdateAutoTopupOverrideRequestBody
from ..types.update_credit_bundle_request_body import UpdateCreditBundleRequestBody
from ..types.update_pay_in_advance_request_body import UpdatePayInAdvanceRequestBody
from .raw_client import AsyncRawCheckoutClient, RawCheckoutClient
from .types.cancel_subscription_response import CancelSubscriptionResponse
from .types.checkout_internal_response import CheckoutInternalResponse
from .types.get_checkout_data_response import GetCheckoutDataResponse
from .types.get_company_billing_details_response import GetCompanyBillingDetailsResponse
from .types.manage_plan_response import ManagePlanResponse
from .types.preview_checkout_internal_response import PreviewCheckoutInternalResponse
from .types.preview_manage_plan_response import PreviewManagePlanResponse
from .types.update_company_billing_details_response import UpdateCompanyBillingDetailsResponse
from .types.update_customer_subscription_trial_end_response import UpdateCustomerSubscriptionTrialEndResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CheckoutClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCheckoutClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCheckoutClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCheckoutClient
        """
        return self._raw_client

    def internal(
        self,
        *,
        add_on_ids: typing.Sequence[UpdateAddOnRequestBody],
        auto_topup_overrides: typing.Sequence[UpdateAutoTopupOverrideRequestBody],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        new_plan_id: str,
        new_price_id: str,
        pay_in_advance: typing.Sequence[UpdatePayInAdvanceRequestBody],
        skip_trial: bool,
        billing_entity_id: typing.Optional[str] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        opt_in_accepted: typing.Optional[bool] = OMIT,
        payment_method_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutInternalResponse:
        """
        Parameters
        ----------
        add_on_ids : typing.Sequence[UpdateAddOnRequestBody]

        auto_topup_overrides : typing.Sequence[UpdateAutoTopupOverrideRequestBody]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        new_plan_id : str

        new_price_id : str

        pay_in_advance : typing.Sequence[UpdatePayInAdvanceRequestBody]

        skip_trial : bool

        billing_entity_id : typing.Optional[str]

        coupon_external_id : typing.Optional[str]

        opt_in_accepted : typing.Optional[bool]

        payment_method_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutInternalResponse
            Created

        Examples
        --------
        from schematic import (
            CheckoutFieldValue,
            Schematic,
            UpdateAddOnRequestBody,
            UpdateAutoTopupOverrideRequestBody,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.internal(
            add_on_ids=[
                UpdateAddOnRequestBody(
                    add_on_id="add_on_id",
                    price_id="price_id",
                )
            ],
            auto_topup_overrides=[
                UpdateAutoTopupOverrideRequestBody(
                    plan_credit_grant_id="plan_credit_grant_id",
                )
            ],
            company_id="company_id",
            credit_bundles=[
                UpdateCreditBundleRequestBody(
                    bundle_id="bundle_id",
                    quantity=1000000,
                )
            ],
            custom_field_values=[
                CheckoutFieldValue(
                    id="id",
                    value="value",
                )
            ],
            new_plan_id="new_plan_id",
            new_price_id="new_price_id",
            pay_in_advance=[
                UpdatePayInAdvanceRequestBody(
                    price_id="price_id",
                    quantity=1000000,
                )
            ],
            skip_trial=True,
        )
        """
        _response = self._raw_client.internal(
            add_on_ids=add_on_ids,
            auto_topup_overrides=auto_topup_overrides,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            new_plan_id=new_plan_id,
            new_price_id=new_price_id,
            pay_in_advance=pay_in_advance,
            skip_trial=skip_trial,
            billing_entity_id=billing_entity_id,
            coupon_external_id=coupon_external_id,
            opt_in_accepted=opt_in_accepted,
            payment_method_id=payment_method_id,
            promo_code=promo_code,
            request_options=request_options,
        )
        return _response.data

    def get_checkout_data(
        self,
        *,
        company_id: str,
        currency: typing.Optional[str] = OMIT,
        selected_plan_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCheckoutDataResponse:
        """
        Parameters
        ----------
        company_id : str

        currency : typing.Optional[str]

        selected_plan_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCheckoutDataResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.get_checkout_data(
            company_id="company_id",
        )
        """
        _response = self._raw_client.get_checkout_data(
            company_id=company_id, currency=currency, selected_plan_id=selected_plan_id, request_options=request_options
        )
        return _response.data

    def preview_checkout_internal(
        self,
        *,
        add_on_ids: typing.Sequence[UpdateAddOnRequestBody],
        auto_topup_overrides: typing.Sequence[UpdateAutoTopupOverrideRequestBody],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        new_plan_id: str,
        new_price_id: str,
        pay_in_advance: typing.Sequence[UpdatePayInAdvanceRequestBody],
        skip_trial: bool,
        billing_entity_id: typing.Optional[str] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        opt_in_accepted: typing.Optional[bool] = OMIT,
        payment_method_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreviewCheckoutInternalResponse:
        """
        Parameters
        ----------
        add_on_ids : typing.Sequence[UpdateAddOnRequestBody]

        auto_topup_overrides : typing.Sequence[UpdateAutoTopupOverrideRequestBody]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        new_plan_id : str

        new_price_id : str

        pay_in_advance : typing.Sequence[UpdatePayInAdvanceRequestBody]

        skip_trial : bool

        billing_entity_id : typing.Optional[str]

        coupon_external_id : typing.Optional[str]

        opt_in_accepted : typing.Optional[bool]

        payment_method_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreviewCheckoutInternalResponse
            OK

        Examples
        --------
        from schematic import (
            CheckoutFieldValue,
            Schematic,
            UpdateAddOnRequestBody,
            UpdateAutoTopupOverrideRequestBody,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.preview_checkout_internal(
            add_on_ids=[
                UpdateAddOnRequestBody(
                    add_on_id="add_on_id",
                    price_id="price_id",
                )
            ],
            auto_topup_overrides=[
                UpdateAutoTopupOverrideRequestBody(
                    plan_credit_grant_id="plan_credit_grant_id",
                )
            ],
            company_id="company_id",
            credit_bundles=[
                UpdateCreditBundleRequestBody(
                    bundle_id="bundle_id",
                    quantity=1000000,
                )
            ],
            custom_field_values=[
                CheckoutFieldValue(
                    id="id",
                    value="value",
                )
            ],
            new_plan_id="new_plan_id",
            new_price_id="new_price_id",
            pay_in_advance=[
                UpdatePayInAdvanceRequestBody(
                    price_id="price_id",
                    quantity=1000000,
                )
            ],
            skip_trial=True,
        )
        """
        _response = self._raw_client.preview_checkout_internal(
            add_on_ids=add_on_ids,
            auto_topup_overrides=auto_topup_overrides,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            new_plan_id=new_plan_id,
            new_price_id=new_price_id,
            pay_in_advance=pay_in_advance,
            skip_trial=skip_trial,
            billing_entity_id=billing_entity_id,
            coupon_external_id=coupon_external_id,
            opt_in_accepted=opt_in_accepted,
            payment_method_id=payment_method_id,
            promo_code=promo_code,
            request_options=request_options,
        )
        return _response.data

    def get_company_billing_details(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCompanyBillingDetailsResponse:
        """
        Parameters
        ----------
        company_id : str
            company_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCompanyBillingDetailsResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.get_company_billing_details(
            company_id="company_id",
        )
        """
        _response = self._raw_client.get_company_billing_details(company_id, request_options=request_options)
        return _response.data

    def update_company_billing_details(
        self,
        company_id: str,
        *,
        values: typing.Sequence[CheckoutFieldValue],
        address: typing.Optional[CustomerBillingAddress] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        tax_id: typing.Optional[TaxIdInput] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCompanyBillingDetailsResponse:
        """
        Parameters
        ----------
        company_id : str
            company_id

        values : typing.Sequence[CheckoutFieldValue]

        address : typing.Optional[CustomerBillingAddress]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        tax_id : typing.Optional[TaxIdInput]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCompanyBillingDetailsResponse
            OK

        Examples
        --------
        from schematic import CheckoutFieldValue, Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.update_company_billing_details(
            company_id="company_id",
            values=[
                CheckoutFieldValue(
                    id="id",
                    value="value",
                )
            ],
        )
        """
        _response = self._raw_client.update_company_billing_details(
            company_id,
            values=values,
            address=address,
            email=email,
            phone=phone,
            tax_id=tax_id,
            request_options=request_options,
        )
        return _response.data

    def manage_plan(
        self,
        *,
        add_on_selections: typing.Sequence[PlanSelection],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        pay_in_advance_entitlements: typing.Sequence[UpdatePayInAdvanceRequestBody],
        activate_on_payment: typing.Optional[bool] = OMIT,
        base_plan_id: typing.Optional[str] = OMIT,
        base_plan_price_id: typing.Optional[str] = OMIT,
        base_plan_version_id: typing.Optional[str] = OMIT,
        billing_cycle_anchor: typing.Optional[dt.datetime] = OMIT,
        billing_email: typing.Optional[str] = OMIT,
        billing_entity_id: typing.Optional[str] = OMIT,
        cancel_immediately: typing.Optional[bool] = OMIT,
        collection_method: typing.Optional[BillingCollectionMethod] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        days_until_due: typing.Optional[int] = OMIT,
        payment_method_external_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        prorate_first_period: typing.Optional[bool] = OMIT,
        send_invoice: typing.Optional[bool] = OMIT,
        trial_end: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ManagePlanResponse:
        """
        Parameters
        ----------
        add_on_selections : typing.Sequence[PlanSelection]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        pay_in_advance_entitlements : typing.Sequence[UpdatePayInAdvanceRequestBody]

        activate_on_payment : typing.Optional[bool]
            If true, the company gets the plan only once the first invoice is paid. Only applies to an invoiced subscription. Defaults to false.

        base_plan_id : typing.Optional[str]

        base_plan_price_id : typing.Optional[str]

        base_plan_version_id : typing.Optional[str]

        billing_cycle_anchor : typing.Optional[dt.datetime]
            The date the subscription's billing period renews on. Only honored when starting a new subscription; changing the anchor on an existing subscription is not supported.

        billing_email : typing.Optional[str]
            Address the invoice is sent to. Required when collection_method is send_invoice.

        billing_entity_id : typing.Optional[str]
            The company that pays for this subscription. Must already have a Stripe customer. Only honored when starting a new subscription.

        cancel_immediately : typing.Optional[bool]
            If false, subscription cancels at period end. Only applies when removing all plans. Defaults to true.

        collection_method : typing.Optional[BillingCollectionMethod]
            How the subscription is paid: charged to a payment method on file, or invoiced with payment terms. Invoicing is only available when starting a new subscription. Defaults to charge_automatically.

        coupon_external_id : typing.Optional[str]

        days_until_due : typing.Optional[int]
            Payment terms in days for an invoiced subscription. Defaults to 30.

        payment_method_external_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        prorate : typing.Optional[bool]
            If true and cancel_immediately is true, issue prorated credit. Only applies when removing all plans. Defaults to true.

        prorate_first_period : typing.Optional[bool]
            When true, the partial period between the subscription starting and its renewal date is billed pro rata straight away. When false that period is free and no invoice is raised until the renewal date. Only applies alongside billing_cycle_anchor. Defaults to true.

        send_invoice : typing.Optional[bool]
            Whether Stripe emails the invoice when it is finalized. Only applies to an invoiced subscription. Defaults to true.

        trial_end : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ManagePlanResponse
            OK

        Examples
        --------
        from schematic import (
            CheckoutFieldValue,
            PlanSelection,
            Schematic,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.manage_plan(
            add_on_selections=[
                PlanSelection(
                    plan_id="plan_id",
                )
            ],
            company_id="company_id",
            credit_bundles=[
                UpdateCreditBundleRequestBody(
                    bundle_id="bundle_id",
                    quantity=1000000,
                )
            ],
            custom_field_values=[
                CheckoutFieldValue(
                    id="id",
                    value="value",
                )
            ],
            pay_in_advance_entitlements=[
                UpdatePayInAdvanceRequestBody(
                    price_id="price_id",
                    quantity=1000000,
                )
            ],
        )
        """
        _response = self._raw_client.manage_plan(
            add_on_selections=add_on_selections,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            pay_in_advance_entitlements=pay_in_advance_entitlements,
            activate_on_payment=activate_on_payment,
            base_plan_id=base_plan_id,
            base_plan_price_id=base_plan_price_id,
            base_plan_version_id=base_plan_version_id,
            billing_cycle_anchor=billing_cycle_anchor,
            billing_email=billing_email,
            billing_entity_id=billing_entity_id,
            cancel_immediately=cancel_immediately,
            collection_method=collection_method,
            coupon_external_id=coupon_external_id,
            days_until_due=days_until_due,
            payment_method_external_id=payment_method_external_id,
            promo_code=promo_code,
            prorate=prorate,
            prorate_first_period=prorate_first_period,
            send_invoice=send_invoice,
            trial_end=trial_end,
            request_options=request_options,
        )
        return _response.data

    def preview_manage_plan(
        self,
        *,
        add_on_selections: typing.Sequence[PlanSelection],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        pay_in_advance_entitlements: typing.Sequence[UpdatePayInAdvanceRequestBody],
        activate_on_payment: typing.Optional[bool] = OMIT,
        base_plan_id: typing.Optional[str] = OMIT,
        base_plan_price_id: typing.Optional[str] = OMIT,
        base_plan_version_id: typing.Optional[str] = OMIT,
        billing_cycle_anchor: typing.Optional[dt.datetime] = OMIT,
        billing_email: typing.Optional[str] = OMIT,
        billing_entity_id: typing.Optional[str] = OMIT,
        cancel_immediately: typing.Optional[bool] = OMIT,
        collection_method: typing.Optional[BillingCollectionMethod] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        days_until_due: typing.Optional[int] = OMIT,
        payment_method_external_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        prorate_first_period: typing.Optional[bool] = OMIT,
        send_invoice: typing.Optional[bool] = OMIT,
        trial_end: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreviewManagePlanResponse:
        """
        Parameters
        ----------
        add_on_selections : typing.Sequence[PlanSelection]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        pay_in_advance_entitlements : typing.Sequence[UpdatePayInAdvanceRequestBody]

        activate_on_payment : typing.Optional[bool]
            If true, the company gets the plan only once the first invoice is paid. Only applies to an invoiced subscription. Defaults to false.

        base_plan_id : typing.Optional[str]

        base_plan_price_id : typing.Optional[str]

        base_plan_version_id : typing.Optional[str]

        billing_cycle_anchor : typing.Optional[dt.datetime]
            The date the subscription's billing period renews on. Only honored when starting a new subscription; changing the anchor on an existing subscription is not supported.

        billing_email : typing.Optional[str]
            Address the invoice is sent to. Required when collection_method is send_invoice.

        billing_entity_id : typing.Optional[str]
            The company that pays for this subscription. Must already have a Stripe customer. Only honored when starting a new subscription.

        cancel_immediately : typing.Optional[bool]
            If false, subscription cancels at period end. Only applies when removing all plans. Defaults to true.

        collection_method : typing.Optional[BillingCollectionMethod]
            How the subscription is paid: charged to a payment method on file, or invoiced with payment terms. Invoicing is only available when starting a new subscription. Defaults to charge_automatically.

        coupon_external_id : typing.Optional[str]

        days_until_due : typing.Optional[int]
            Payment terms in days for an invoiced subscription. Defaults to 30.

        payment_method_external_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        prorate : typing.Optional[bool]
            If true and cancel_immediately is true, issue prorated credit. Only applies when removing all plans. Defaults to true.

        prorate_first_period : typing.Optional[bool]
            When true, the partial period between the subscription starting and its renewal date is billed pro rata straight away. When false that period is free and no invoice is raised until the renewal date. Only applies alongside billing_cycle_anchor. Defaults to true.

        send_invoice : typing.Optional[bool]
            Whether Stripe emails the invoice when it is finalized. Only applies to an invoiced subscription. Defaults to true.

        trial_end : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreviewManagePlanResponse
            OK

        Examples
        --------
        from schematic import (
            CheckoutFieldValue,
            PlanSelection,
            Schematic,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.preview_manage_plan(
            add_on_selections=[
                PlanSelection(
                    plan_id="plan_id",
                )
            ],
            company_id="company_id",
            credit_bundles=[
                UpdateCreditBundleRequestBody(
                    bundle_id="bundle_id",
                    quantity=1000000,
                )
            ],
            custom_field_values=[
                CheckoutFieldValue(
                    id="id",
                    value="value",
                )
            ],
            pay_in_advance_entitlements=[
                UpdatePayInAdvanceRequestBody(
                    price_id="price_id",
                    quantity=1000000,
                )
            ],
        )
        """
        _response = self._raw_client.preview_manage_plan(
            add_on_selections=add_on_selections,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            pay_in_advance_entitlements=pay_in_advance_entitlements,
            activate_on_payment=activate_on_payment,
            base_plan_id=base_plan_id,
            base_plan_price_id=base_plan_price_id,
            base_plan_version_id=base_plan_version_id,
            billing_cycle_anchor=billing_cycle_anchor,
            billing_email=billing_email,
            billing_entity_id=billing_entity_id,
            cancel_immediately=cancel_immediately,
            collection_method=collection_method,
            coupon_external_id=coupon_external_id,
            days_until_due=days_until_due,
            payment_method_external_id=payment_method_external_id,
            promo_code=promo_code,
            prorate=prorate,
            prorate_first_period=prorate_first_period,
            send_invoice=send_invoice,
            trial_end=trial_end,
            request_options=request_options,
        )
        return _response.data

    def cancel_subscription(
        self,
        *,
        company_id: str,
        cancel_immediately: typing.Optional[bool] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelSubscriptionResponse:
        """
        Parameters
        ----------
        company_id : str

        cancel_immediately : typing.Optional[bool]
            If false, subscription cancels at period end. Defaults to true.

        prorate : typing.Optional[bool]
            If true and cancel_immediately is true, issue prorated credit. Defaults to true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelSubscriptionResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.cancel_subscription(
            company_id="company_id",
        )
        """
        _response = self._raw_client.cancel_subscription(
            company_id=company_id,
            cancel_immediately=cancel_immediately,
            prorate=prorate,
            request_options=request_options,
        )
        return _response.data

    def update_customer_subscription_trial_end(
        self,
        subscription_id: str,
        *,
        trial_end: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCustomerSubscriptionTrialEndResponse:
        """
        Parameters
        ----------
        subscription_id : str
            subscription_id

        trial_end : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCustomerSubscriptionTrialEndResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.checkout.update_customer_subscription_trial_end(
            subscription_id="subscription_id",
        )
        """
        _response = self._raw_client.update_customer_subscription_trial_end(
            subscription_id, trial_end=trial_end, request_options=request_options
        )
        return _response.data


class AsyncCheckoutClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCheckoutClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCheckoutClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCheckoutClient
        """
        return self._raw_client

    async def internal(
        self,
        *,
        add_on_ids: typing.Sequence[UpdateAddOnRequestBody],
        auto_topup_overrides: typing.Sequence[UpdateAutoTopupOverrideRequestBody],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        new_plan_id: str,
        new_price_id: str,
        pay_in_advance: typing.Sequence[UpdatePayInAdvanceRequestBody],
        skip_trial: bool,
        billing_entity_id: typing.Optional[str] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        opt_in_accepted: typing.Optional[bool] = OMIT,
        payment_method_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CheckoutInternalResponse:
        """
        Parameters
        ----------
        add_on_ids : typing.Sequence[UpdateAddOnRequestBody]

        auto_topup_overrides : typing.Sequence[UpdateAutoTopupOverrideRequestBody]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        new_plan_id : str

        new_price_id : str

        pay_in_advance : typing.Sequence[UpdatePayInAdvanceRequestBody]

        skip_trial : bool

        billing_entity_id : typing.Optional[str]

        coupon_external_id : typing.Optional[str]

        opt_in_accepted : typing.Optional[bool]

        payment_method_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CheckoutInternalResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import (
            AsyncSchematic,
            CheckoutFieldValue,
            UpdateAddOnRequestBody,
            UpdateAutoTopupOverrideRequestBody,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.internal(
                add_on_ids=[
                    UpdateAddOnRequestBody(
                        add_on_id="add_on_id",
                        price_id="price_id",
                    )
                ],
                auto_topup_overrides=[
                    UpdateAutoTopupOverrideRequestBody(
                        plan_credit_grant_id="plan_credit_grant_id",
                    )
                ],
                company_id="company_id",
                credit_bundles=[
                    UpdateCreditBundleRequestBody(
                        bundle_id="bundle_id",
                        quantity=1000000,
                    )
                ],
                custom_field_values=[
                    CheckoutFieldValue(
                        id="id",
                        value="value",
                    )
                ],
                new_plan_id="new_plan_id",
                new_price_id="new_price_id",
                pay_in_advance=[
                    UpdatePayInAdvanceRequestBody(
                        price_id="price_id",
                        quantity=1000000,
                    )
                ],
                skip_trial=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.internal(
            add_on_ids=add_on_ids,
            auto_topup_overrides=auto_topup_overrides,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            new_plan_id=new_plan_id,
            new_price_id=new_price_id,
            pay_in_advance=pay_in_advance,
            skip_trial=skip_trial,
            billing_entity_id=billing_entity_id,
            coupon_external_id=coupon_external_id,
            opt_in_accepted=opt_in_accepted,
            payment_method_id=payment_method_id,
            promo_code=promo_code,
            request_options=request_options,
        )
        return _response.data

    async def get_checkout_data(
        self,
        *,
        company_id: str,
        currency: typing.Optional[str] = OMIT,
        selected_plan_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetCheckoutDataResponse:
        """
        Parameters
        ----------
        company_id : str

        currency : typing.Optional[str]

        selected_plan_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCheckoutDataResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.get_checkout_data(
                company_id="company_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_checkout_data(
            company_id=company_id, currency=currency, selected_plan_id=selected_plan_id, request_options=request_options
        )
        return _response.data

    async def preview_checkout_internal(
        self,
        *,
        add_on_ids: typing.Sequence[UpdateAddOnRequestBody],
        auto_topup_overrides: typing.Sequence[UpdateAutoTopupOverrideRequestBody],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        new_plan_id: str,
        new_price_id: str,
        pay_in_advance: typing.Sequence[UpdatePayInAdvanceRequestBody],
        skip_trial: bool,
        billing_entity_id: typing.Optional[str] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        opt_in_accepted: typing.Optional[bool] = OMIT,
        payment_method_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreviewCheckoutInternalResponse:
        """
        Parameters
        ----------
        add_on_ids : typing.Sequence[UpdateAddOnRequestBody]

        auto_topup_overrides : typing.Sequence[UpdateAutoTopupOverrideRequestBody]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        new_plan_id : str

        new_price_id : str

        pay_in_advance : typing.Sequence[UpdatePayInAdvanceRequestBody]

        skip_trial : bool

        billing_entity_id : typing.Optional[str]

        coupon_external_id : typing.Optional[str]

        opt_in_accepted : typing.Optional[bool]

        payment_method_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreviewCheckoutInternalResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import (
            AsyncSchematic,
            CheckoutFieldValue,
            UpdateAddOnRequestBody,
            UpdateAutoTopupOverrideRequestBody,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.preview_checkout_internal(
                add_on_ids=[
                    UpdateAddOnRequestBody(
                        add_on_id="add_on_id",
                        price_id="price_id",
                    )
                ],
                auto_topup_overrides=[
                    UpdateAutoTopupOverrideRequestBody(
                        plan_credit_grant_id="plan_credit_grant_id",
                    )
                ],
                company_id="company_id",
                credit_bundles=[
                    UpdateCreditBundleRequestBody(
                        bundle_id="bundle_id",
                        quantity=1000000,
                    )
                ],
                custom_field_values=[
                    CheckoutFieldValue(
                        id="id",
                        value="value",
                    )
                ],
                new_plan_id="new_plan_id",
                new_price_id="new_price_id",
                pay_in_advance=[
                    UpdatePayInAdvanceRequestBody(
                        price_id="price_id",
                        quantity=1000000,
                    )
                ],
                skip_trial=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preview_checkout_internal(
            add_on_ids=add_on_ids,
            auto_topup_overrides=auto_topup_overrides,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            new_plan_id=new_plan_id,
            new_price_id=new_price_id,
            pay_in_advance=pay_in_advance,
            skip_trial=skip_trial,
            billing_entity_id=billing_entity_id,
            coupon_external_id=coupon_external_id,
            opt_in_accepted=opt_in_accepted,
            payment_method_id=payment_method_id,
            promo_code=promo_code,
            request_options=request_options,
        )
        return _response.data

    async def get_company_billing_details(
        self, company_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCompanyBillingDetailsResponse:
        """
        Parameters
        ----------
        company_id : str
            company_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCompanyBillingDetailsResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.get_company_billing_details(
                company_id="company_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_company_billing_details(company_id, request_options=request_options)
        return _response.data

    async def update_company_billing_details(
        self,
        company_id: str,
        *,
        values: typing.Sequence[CheckoutFieldValue],
        address: typing.Optional[CustomerBillingAddress] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        tax_id: typing.Optional[TaxIdInput] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCompanyBillingDetailsResponse:
        """
        Parameters
        ----------
        company_id : str
            company_id

        values : typing.Sequence[CheckoutFieldValue]

        address : typing.Optional[CustomerBillingAddress]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        tax_id : typing.Optional[TaxIdInput]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCompanyBillingDetailsResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic, CheckoutFieldValue

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.update_company_billing_details(
                company_id="company_id",
                values=[
                    CheckoutFieldValue(
                        id="id",
                        value="value",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_company_billing_details(
            company_id,
            values=values,
            address=address,
            email=email,
            phone=phone,
            tax_id=tax_id,
            request_options=request_options,
        )
        return _response.data

    async def manage_plan(
        self,
        *,
        add_on_selections: typing.Sequence[PlanSelection],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        pay_in_advance_entitlements: typing.Sequence[UpdatePayInAdvanceRequestBody],
        activate_on_payment: typing.Optional[bool] = OMIT,
        base_plan_id: typing.Optional[str] = OMIT,
        base_plan_price_id: typing.Optional[str] = OMIT,
        base_plan_version_id: typing.Optional[str] = OMIT,
        billing_cycle_anchor: typing.Optional[dt.datetime] = OMIT,
        billing_email: typing.Optional[str] = OMIT,
        billing_entity_id: typing.Optional[str] = OMIT,
        cancel_immediately: typing.Optional[bool] = OMIT,
        collection_method: typing.Optional[BillingCollectionMethod] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        days_until_due: typing.Optional[int] = OMIT,
        payment_method_external_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        prorate_first_period: typing.Optional[bool] = OMIT,
        send_invoice: typing.Optional[bool] = OMIT,
        trial_end: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ManagePlanResponse:
        """
        Parameters
        ----------
        add_on_selections : typing.Sequence[PlanSelection]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        pay_in_advance_entitlements : typing.Sequence[UpdatePayInAdvanceRequestBody]

        activate_on_payment : typing.Optional[bool]
            If true, the company gets the plan only once the first invoice is paid. Only applies to an invoiced subscription. Defaults to false.

        base_plan_id : typing.Optional[str]

        base_plan_price_id : typing.Optional[str]

        base_plan_version_id : typing.Optional[str]

        billing_cycle_anchor : typing.Optional[dt.datetime]
            The date the subscription's billing period renews on. Only honored when starting a new subscription; changing the anchor on an existing subscription is not supported.

        billing_email : typing.Optional[str]
            Address the invoice is sent to. Required when collection_method is send_invoice.

        billing_entity_id : typing.Optional[str]
            The company that pays for this subscription. Must already have a Stripe customer. Only honored when starting a new subscription.

        cancel_immediately : typing.Optional[bool]
            If false, subscription cancels at period end. Only applies when removing all plans. Defaults to true.

        collection_method : typing.Optional[BillingCollectionMethod]
            How the subscription is paid: charged to a payment method on file, or invoiced with payment terms. Invoicing is only available when starting a new subscription. Defaults to charge_automatically.

        coupon_external_id : typing.Optional[str]

        days_until_due : typing.Optional[int]
            Payment terms in days for an invoiced subscription. Defaults to 30.

        payment_method_external_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        prorate : typing.Optional[bool]
            If true and cancel_immediately is true, issue prorated credit. Only applies when removing all plans. Defaults to true.

        prorate_first_period : typing.Optional[bool]
            When true, the partial period between the subscription starting and its renewal date is billed pro rata straight away. When false that period is free and no invoice is raised until the renewal date. Only applies alongside billing_cycle_anchor. Defaults to true.

        send_invoice : typing.Optional[bool]
            Whether Stripe emails the invoice when it is finalized. Only applies to an invoiced subscription. Defaults to true.

        trial_end : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ManagePlanResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import (
            AsyncSchematic,
            CheckoutFieldValue,
            PlanSelection,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.manage_plan(
                add_on_selections=[
                    PlanSelection(
                        plan_id="plan_id",
                    )
                ],
                company_id="company_id",
                credit_bundles=[
                    UpdateCreditBundleRequestBody(
                        bundle_id="bundle_id",
                        quantity=1000000,
                    )
                ],
                custom_field_values=[
                    CheckoutFieldValue(
                        id="id",
                        value="value",
                    )
                ],
                pay_in_advance_entitlements=[
                    UpdatePayInAdvanceRequestBody(
                        price_id="price_id",
                        quantity=1000000,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.manage_plan(
            add_on_selections=add_on_selections,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            pay_in_advance_entitlements=pay_in_advance_entitlements,
            activate_on_payment=activate_on_payment,
            base_plan_id=base_plan_id,
            base_plan_price_id=base_plan_price_id,
            base_plan_version_id=base_plan_version_id,
            billing_cycle_anchor=billing_cycle_anchor,
            billing_email=billing_email,
            billing_entity_id=billing_entity_id,
            cancel_immediately=cancel_immediately,
            collection_method=collection_method,
            coupon_external_id=coupon_external_id,
            days_until_due=days_until_due,
            payment_method_external_id=payment_method_external_id,
            promo_code=promo_code,
            prorate=prorate,
            prorate_first_period=prorate_first_period,
            send_invoice=send_invoice,
            trial_end=trial_end,
            request_options=request_options,
        )
        return _response.data

    async def preview_manage_plan(
        self,
        *,
        add_on_selections: typing.Sequence[PlanSelection],
        company_id: str,
        credit_bundles: typing.Sequence[UpdateCreditBundleRequestBody],
        custom_field_values: typing.Sequence[CheckoutFieldValue],
        pay_in_advance_entitlements: typing.Sequence[UpdatePayInAdvanceRequestBody],
        activate_on_payment: typing.Optional[bool] = OMIT,
        base_plan_id: typing.Optional[str] = OMIT,
        base_plan_price_id: typing.Optional[str] = OMIT,
        base_plan_version_id: typing.Optional[str] = OMIT,
        billing_cycle_anchor: typing.Optional[dt.datetime] = OMIT,
        billing_email: typing.Optional[str] = OMIT,
        billing_entity_id: typing.Optional[str] = OMIT,
        cancel_immediately: typing.Optional[bool] = OMIT,
        collection_method: typing.Optional[BillingCollectionMethod] = OMIT,
        coupon_external_id: typing.Optional[str] = OMIT,
        days_until_due: typing.Optional[int] = OMIT,
        payment_method_external_id: typing.Optional[str] = OMIT,
        promo_code: typing.Optional[str] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        prorate_first_period: typing.Optional[bool] = OMIT,
        send_invoice: typing.Optional[bool] = OMIT,
        trial_end: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreviewManagePlanResponse:
        """
        Parameters
        ----------
        add_on_selections : typing.Sequence[PlanSelection]

        company_id : str

        credit_bundles : typing.Sequence[UpdateCreditBundleRequestBody]

        custom_field_values : typing.Sequence[CheckoutFieldValue]

        pay_in_advance_entitlements : typing.Sequence[UpdatePayInAdvanceRequestBody]

        activate_on_payment : typing.Optional[bool]
            If true, the company gets the plan only once the first invoice is paid. Only applies to an invoiced subscription. Defaults to false.

        base_plan_id : typing.Optional[str]

        base_plan_price_id : typing.Optional[str]

        base_plan_version_id : typing.Optional[str]

        billing_cycle_anchor : typing.Optional[dt.datetime]
            The date the subscription's billing period renews on. Only honored when starting a new subscription; changing the anchor on an existing subscription is not supported.

        billing_email : typing.Optional[str]
            Address the invoice is sent to. Required when collection_method is send_invoice.

        billing_entity_id : typing.Optional[str]
            The company that pays for this subscription. Must already have a Stripe customer. Only honored when starting a new subscription.

        cancel_immediately : typing.Optional[bool]
            If false, subscription cancels at period end. Only applies when removing all plans. Defaults to true.

        collection_method : typing.Optional[BillingCollectionMethod]
            How the subscription is paid: charged to a payment method on file, or invoiced with payment terms. Invoicing is only available when starting a new subscription. Defaults to charge_automatically.

        coupon_external_id : typing.Optional[str]

        days_until_due : typing.Optional[int]
            Payment terms in days for an invoiced subscription. Defaults to 30.

        payment_method_external_id : typing.Optional[str]

        promo_code : typing.Optional[str]

        prorate : typing.Optional[bool]
            If true and cancel_immediately is true, issue prorated credit. Only applies when removing all plans. Defaults to true.

        prorate_first_period : typing.Optional[bool]
            When true, the partial period between the subscription starting and its renewal date is billed pro rata straight away. When false that period is free and no invoice is raised until the renewal date. Only applies alongside billing_cycle_anchor. Defaults to true.

        send_invoice : typing.Optional[bool]
            Whether Stripe emails the invoice when it is finalized. Only applies to an invoiced subscription. Defaults to true.

        trial_end : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreviewManagePlanResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import (
            AsyncSchematic,
            CheckoutFieldValue,
            PlanSelection,
            UpdateCreditBundleRequestBody,
            UpdatePayInAdvanceRequestBody,
        )

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.preview_manage_plan(
                add_on_selections=[
                    PlanSelection(
                        plan_id="plan_id",
                    )
                ],
                company_id="company_id",
                credit_bundles=[
                    UpdateCreditBundleRequestBody(
                        bundle_id="bundle_id",
                        quantity=1000000,
                    )
                ],
                custom_field_values=[
                    CheckoutFieldValue(
                        id="id",
                        value="value",
                    )
                ],
                pay_in_advance_entitlements=[
                    UpdatePayInAdvanceRequestBody(
                        price_id="price_id",
                        quantity=1000000,
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.preview_manage_plan(
            add_on_selections=add_on_selections,
            company_id=company_id,
            credit_bundles=credit_bundles,
            custom_field_values=custom_field_values,
            pay_in_advance_entitlements=pay_in_advance_entitlements,
            activate_on_payment=activate_on_payment,
            base_plan_id=base_plan_id,
            base_plan_price_id=base_plan_price_id,
            base_plan_version_id=base_plan_version_id,
            billing_cycle_anchor=billing_cycle_anchor,
            billing_email=billing_email,
            billing_entity_id=billing_entity_id,
            cancel_immediately=cancel_immediately,
            collection_method=collection_method,
            coupon_external_id=coupon_external_id,
            days_until_due=days_until_due,
            payment_method_external_id=payment_method_external_id,
            promo_code=promo_code,
            prorate=prorate,
            prorate_first_period=prorate_first_period,
            send_invoice=send_invoice,
            trial_end=trial_end,
            request_options=request_options,
        )
        return _response.data

    async def cancel_subscription(
        self,
        *,
        company_id: str,
        cancel_immediately: typing.Optional[bool] = OMIT,
        prorate: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CancelSubscriptionResponse:
        """
        Parameters
        ----------
        company_id : str

        cancel_immediately : typing.Optional[bool]
            If false, subscription cancels at period end. Defaults to true.

        prorate : typing.Optional[bool]
            If true and cancel_immediately is true, issue prorated credit. Defaults to true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelSubscriptionResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.cancel_subscription(
                company_id="company_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_subscription(
            company_id=company_id,
            cancel_immediately=cancel_immediately,
            prorate=prorate,
            request_options=request_options,
        )
        return _response.data

    async def update_customer_subscription_trial_end(
        self,
        subscription_id: str,
        *,
        trial_end: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCustomerSubscriptionTrialEndResponse:
        """
        Parameters
        ----------
        subscription_id : str
            subscription_id

        trial_end : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCustomerSubscriptionTrialEndResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.checkout.update_customer_subscription_trial_end(
                subscription_id="subscription_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_customer_subscription_trial_end(
            subscription_id, trial_end=trial_end, request_options=request_options
        )
        return _response.data
