# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.time_series_granularity import TimeSeriesGranularity
from .raw_client import AsyncRawInsightsClient, RawInsightsClient
from .types.get_activity_response import GetActivityResponse
from .types.get_environment_feature_usage_time_series_response import GetEnvironmentFeatureUsageTimeSeriesResponse
from .types.get_environment_trait_usage_time_series_response import GetEnvironmentTraitUsageTimeSeriesResponse
from .types.get_plan_growth_response import GetPlanGrowthResponse
from .types.get_summary_response import GetSummaryResponse
from .types.get_top_features_by_usage_response import GetTopFeaturesByUsageResponse


class InsightsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInsightsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInsightsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInsightsClient
        """
        return self._raw_client

    def get_activity(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GetActivityResponse:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetActivityResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.insights.get_activity(
            limit=1000000,
        )
        """
        _response = self._raw_client.get_activity(limit=limit, request_options=request_options)
        return _response.data

    def get_environment_feature_usage_time_series(
        self,
        *,
        end_time: dt.datetime,
        feature_id: str,
        start_time: dt.datetime,
        granularity: typing.Optional[TimeSeriesGranularity] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetEnvironmentFeatureUsageTimeSeriesResponse:
        """
        Parameters
        ----------
        end_time : dt.datetime

        feature_id : str

        start_time : dt.datetime

        granularity : typing.Optional[TimeSeriesGranularity]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetEnvironmentFeatureUsageTimeSeriesResponse
            OK

        Examples
        --------
        import datetime

        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.insights.get_environment_feature_usage_time_series(
            end_time=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            feature_id="feature_id",
            granularity="daily",
            start_time=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
        )
        """
        _response = self._raw_client.get_environment_feature_usage_time_series(
            end_time=end_time,
            feature_id=feature_id,
            start_time=start_time,
            granularity=granularity,
            request_options=request_options,
        )
        return _response.data

    def get_plan_growth(
        self, *, months: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPlanGrowthResponse:
        """
        Parameters
        ----------
        months : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPlanGrowthResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.insights.get_plan_growth(
            months=1000000,
        )
        """
        _response = self._raw_client.get_plan_growth(months=months, request_options=request_options)
        return _response.data

    def get_summary(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetSummaryResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSummaryResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.insights.get_summary()
        """
        _response = self._raw_client.get_summary(request_options=request_options)
        return _response.data

    def get_top_features_by_usage(
        self,
        *,
        end_time: dt.datetime,
        start_time: dt.datetime,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetTopFeaturesByUsageResponse:
        """
        Parameters
        ----------
        end_time : dt.datetime

        start_time : dt.datetime

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTopFeaturesByUsageResponse
            OK

        Examples
        --------
        import datetime

        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.insights.get_top_features_by_usage(
            end_time=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            limit=1000000,
            start_time=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
        )
        """
        _response = self._raw_client.get_top_features_by_usage(
            end_time=end_time, start_time=start_time, limit=limit, request_options=request_options
        )
        return _response.data

    def get_environment_trait_usage_time_series(
        self,
        *,
        end_time: dt.datetime,
        feature_id: str,
        start_time: dt.datetime,
        granularity: typing.Optional[TimeSeriesGranularity] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetEnvironmentTraitUsageTimeSeriesResponse:
        """
        Parameters
        ----------
        end_time : dt.datetime

        feature_id : str

        start_time : dt.datetime

        granularity : typing.Optional[TimeSeriesGranularity]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetEnvironmentTraitUsageTimeSeriesResponse
            OK

        Examples
        --------
        import datetime

        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.insights.get_environment_trait_usage_time_series(
            end_time=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
            feature_id="feature_id",
            granularity="daily",
            start_time=datetime.datetime.fromisoformat(
                "2024-01-15 09:30:00+00:00",
            ),
        )
        """
        _response = self._raw_client.get_environment_trait_usage_time_series(
            end_time=end_time,
            feature_id=feature_id,
            start_time=start_time,
            granularity=granularity,
            request_options=request_options,
        )
        return _response.data


class AsyncInsightsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInsightsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInsightsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInsightsClient
        """
        return self._raw_client

    async def get_activity(
        self, *, limit: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GetActivityResponse:
        """
        Parameters
        ----------
        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetActivityResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.insights.get_activity(
                limit=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_activity(limit=limit, request_options=request_options)
        return _response.data

    async def get_environment_feature_usage_time_series(
        self,
        *,
        end_time: dt.datetime,
        feature_id: str,
        start_time: dt.datetime,
        granularity: typing.Optional[TimeSeriesGranularity] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetEnvironmentFeatureUsageTimeSeriesResponse:
        """
        Parameters
        ----------
        end_time : dt.datetime

        feature_id : str

        start_time : dt.datetime

        granularity : typing.Optional[TimeSeriesGranularity]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetEnvironmentFeatureUsageTimeSeriesResponse
            OK

        Examples
        --------
        import asyncio
        import datetime

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.insights.get_environment_feature_usage_time_series(
                end_time=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                feature_id="feature_id",
                granularity="daily",
                start_time=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_environment_feature_usage_time_series(
            end_time=end_time,
            feature_id=feature_id,
            start_time=start_time,
            granularity=granularity,
            request_options=request_options,
        )
        return _response.data

    async def get_plan_growth(
        self, *, months: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPlanGrowthResponse:
        """
        Parameters
        ----------
        months : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPlanGrowthResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.insights.get_plan_growth(
                months=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_plan_growth(months=months, request_options=request_options)
        return _response.data

    async def get_summary(self, *, request_options: typing.Optional[RequestOptions] = None) -> GetSummaryResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetSummaryResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.insights.get_summary()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_summary(request_options=request_options)
        return _response.data

    async def get_top_features_by_usage(
        self,
        *,
        end_time: dt.datetime,
        start_time: dt.datetime,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetTopFeaturesByUsageResponse:
        """
        Parameters
        ----------
        end_time : dt.datetime

        start_time : dt.datetime

        limit : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetTopFeaturesByUsageResponse
            OK

        Examples
        --------
        import asyncio
        import datetime

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.insights.get_top_features_by_usage(
                end_time=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                limit=1000000,
                start_time=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_top_features_by_usage(
            end_time=end_time, start_time=start_time, limit=limit, request_options=request_options
        )
        return _response.data

    async def get_environment_trait_usage_time_series(
        self,
        *,
        end_time: dt.datetime,
        feature_id: str,
        start_time: dt.datetime,
        granularity: typing.Optional[TimeSeriesGranularity] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetEnvironmentTraitUsageTimeSeriesResponse:
        """
        Parameters
        ----------
        end_time : dt.datetime

        feature_id : str

        start_time : dt.datetime

        granularity : typing.Optional[TimeSeriesGranularity]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetEnvironmentTraitUsageTimeSeriesResponse
            OK

        Examples
        --------
        import asyncio
        import datetime

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.insights.get_environment_trait_usage_time_series(
                end_time=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
                feature_id="feature_id",
                granularity="daily",
                start_time=datetime.datetime.fromisoformat(
                    "2024-01-15 09:30:00+00:00",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_environment_trait_usage_time_series(
            end_time=end_time,
            feature_id=feature_id,
            start_time=start_time,
            granularity=granularity,
            request_options=request_options,
        )
        return _response.data
