# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .count_company_migrations_params import CountCompanyMigrationsParams
    from .count_company_migrations_response import CountCompanyMigrationsResponse
    from .count_migrations_params import CountMigrationsParams
    from .count_migrations_response import CountMigrationsResponse
    from .get_migration_response import GetMigrationResponse
    from .list_company_migrations_params import ListCompanyMigrationsParams
    from .list_company_migrations_response import ListCompanyMigrationsResponse
    from .list_migrations_params import ListMigrationsParams
    from .list_migrations_response import ListMigrationsResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CountCompanyMigrationsParams": ".count_company_migrations_params",
    "CountCompanyMigrationsResponse": ".count_company_migrations_response",
    "CountMigrationsParams": ".count_migrations_params",
    "CountMigrationsResponse": ".count_migrations_response",
    "GetMigrationResponse": ".get_migration_response",
    "ListCompanyMigrationsParams": ".list_company_migrations_params",
    "ListCompanyMigrationsResponse": ".list_company_migrations_response",
    "ListMigrationsParams": ".list_migrations_params",
    "ListMigrationsResponse": ".list_migrations_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CountCompanyMigrationsParams",
    "CountCompanyMigrationsResponse",
    "CountMigrationsParams",
    "CountMigrationsResponse",
    "GetMigrationResponse",
    "ListCompanyMigrationsParams",
    "ListCompanyMigrationsResponse",
    "ListMigrationsParams",
    "ListMigrationsResponse",
]
