# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.plan_version_company_migration_response_data import PlanVersionCompanyMigrationResponseData
from .list_company_migrations_params import ListCompanyMigrationsParams


class ListCompanyMigrationsResponse(UniversalBaseModel):
    data: typing.List[PlanVersionCompanyMigrationResponseData]
    params: ListCompanyMigrationsParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
