# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .account_member_permission import AccountMemberPermission
from .account_member_role import AccountMemberRole


class AccountMemberResponseData(UniversalBaseModel):
    created_at: dt.datetime
    email: typing.Optional[str] = None
    id: str
    image_url: typing.Optional[str] = None
    name: typing.Optional[str] = None
    permissions: typing.Dict[str, typing.List[AccountMemberPermission]]
    role: typing.Optional[AccountMemberRole] = None
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
