# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AuditLogExportMetadata(UniversalBaseModel):
    actor_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Restrict the export to audit log entries from this actor type
    """

    end_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Restrict the export to audit log entries that started before this time
    """

    notification_email_recipient_email_addresses: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Account member emails to notify when the export completes; empty means the artifact is only retrievable via the API
    """

    q: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text search over audit log entries
    """

    start_time: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Restrict the export to audit log entries that started at or after this time
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
