# This file was auto-generated by Fern from our API Definition.

import typing

BillingCreditGrantZeroedOutReason = typing.Union[
    typing.Literal[
        "customer_archived",
        "expired",
        "integration_uninstalled",
        "manual",
        "plan_change",
        "plan_period_reset",
        "reconciled",
    ],
    typing.Any,
]
