# This file was auto-generated by Fern from our API Definition.

import typing

BillingCreditLedgerAuthority = typing.Union[
    typing.Literal["schematic_authoritative", "external_mirror", "external_rated"], typing.Any
]
