# This file was auto-generated by Fern from our API Definition.

import typing

BillingCreditGrantReason = typing.Union[
    typing.Literal["adjustment", "billing_credit_auto_topup", "free", "plan", "purchased"], typing.Any
]
