# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_arrears_anchor import BillingArrearsAnchor
from .billing_arrears_cadence import BillingArrearsCadence
from .billing_credit_auto_topup_availability import BillingCreditAutoTopupAvailability
from .billing_credit_expiry_type import BillingCreditExpiryType
from .billing_credit_expiry_unit import BillingCreditExpiryUnit
from .billing_credit_response_data import BillingCreditResponseData
from .billing_plan_credit_grant_billing_mode import BillingPlanCreditGrantBillingMode
from .billing_plan_credit_grant_price_tier_response_data import BillingPlanCreditGrantPriceTierResponseData
from .billing_plan_credit_grant_reset_cadence import BillingPlanCreditGrantResetCadence
from .billing_plan_credit_grant_reset_start import BillingPlanCreditGrantResetStart
from .billing_plan_credit_grant_reset_type import BillingPlanCreditGrantResetType
from .billing_price_response_data import BillingPriceResponseData
from .billing_tiers_mode import BillingTiersMode
from .plan_credit_grant_scaling import PlanCreditGrantScaling
from .preview_object_response_data import PreviewObjectResponseData


class BillingPlanCreditGrantResponseData(UniversalBaseModel):
    arrears_anchor: typing.Optional[BillingArrearsAnchor] = pydantic.Field(default=None)
    """
    Which boundary closes a monthly arrears window. Only meaningful when arrears_cadence is monthly.
    """

    arrears_cadence: typing.Optional[BillingArrearsCadence] = pydantic.Field(default=None)
    """
    How often postpaid charges are closed and invoiced. Defaults to end_of_billing_period.
    """

    auto_topup_amount: typing.Optional[int] = None
    auto_topup_amount_type: typing.Optional[str] = None
    auto_topup_availability: BillingCreditAutoTopupAvailability
    auto_topup_enabled: bool = pydantic.Field()
    """
    Derived from auto_topup_availability; use that instead.
    """

    auto_topup_expiry_type: typing.Optional[BillingCreditExpiryType] = None
    auto_topup_expiry_unit: typing.Optional[BillingCreditExpiryUnit] = None
    auto_topup_expiry_unit_count: typing.Optional[int] = None
    auto_topup_self_service: bool = pydantic.Field()
    """
    Derived from auto_topup_availability; use that instead.
    """

    auto_topup_threshold_credits: typing.Optional[int] = None
    auto_topup_threshold_percent: typing.Optional[int] = None
    billing_mode: BillingPlanCreditGrantBillingMode = pydantic.Field()
    """
    Whether the credits are included in the plan price (granted) or billed as their own subscription line at a price per credit (billed).
    """

    can_buy_bundles: bool = pydantic.Field()
    """
    Deprecated: bundle availability is a per-bundle plan compatibility set now; use compatible_plan_ids on credit bundles instead.
    """

    company_credit_amount: int = pydantic.Field()
    """
    Credits granted once per company on top of the per-license amount. Always 0 when scaling is fixed.
    """

    created_at: dt.datetime
    credit: typing.Optional[BillingCreditResponseData] = None
    credit_amount: int
    credit_id: str
    credit_name: str = pydantic.Field()
    """
    Use credit.name from the nested credit object instead
    """

    credit_plural_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Use plural_name from the nested credit object instead
    """

    credit_singular_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Use singular_name from the nested credit object instead
    """

    expiry_type: typing.Optional[BillingCreditExpiryType] = None
    expiry_unit: typing.Optional[BillingCreditExpiryUnit] = None
    expiry_unit_count: typing.Optional[int] = None
    id: str
    license_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The license whose quantity scales this grant. Set only when scaling is per_license.
    """

    overdraft_limit: typing.Optional[float] = pydantic.Field(default=None)
    """
    Optional limit on how far the balance may go below zero, in credits. A floor on the balance, not an allowance per invoice window: consumption is denied once the balance would fall below minus this figure, and stays denied until a new grant lands or the negative balance is settled. Absent means no limit.
    """

    plan: typing.Optional[PreviewObjectResponseData] = None
    plan_id: str
    plan_name: str = pydantic.Field()
    """
    Use plan.name from the nested plan object instead
    """

    plan_version_id: typing.Optional[str] = None
    postpaid_enabled: bool = pydantic.Field()
    """
    Whether consumption may continue past a zero balance, accruing at postpaid_rate_per_unit rather than being denied.
    """

    postpaid_rate_per_unit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Amount charged per credit consumed past zero, in the currency's minor unit. Defaults to the credit's own cost basis when postpaid is enabled without one.
    """

    postpaid_rate_per_unit_decimal: typing.Optional[str] = pydantic.Field(default=None)
    """
    Decimal form of postpaid_rate_per_unit, for rates finer than one minor unit.
    """

    price: typing.Optional[BillingPriceResponseData] = pydantic.Field(default=None)
    """
    The Stripe price a billed grant bills through. Minted when the plan version is published.
    """

    price_tiers: typing.List[BillingPlanCreditGrantPriceTierResponseData] = pydantic.Field()
    """
    Tier table pricing the credits, cheapest bound first. Empty unless billing_mode is billed and the credits are priced on tiers.
    """

    reset_cadence: typing.Optional[BillingPlanCreditGrantResetCadence] = None
    reset_start: typing.Optional[BillingPlanCreditGrantResetStart] = None
    reset_type: typing.Optional[BillingPlanCreditGrantResetType] = None
    rollover_percentage: int = pydantic.Field()
    """
    Percentage of unused credits that carry over when this grant resets. Only meaningful when reset_type is plan_period.
    """

    scaling: PlanCreditGrantScaling = pydantic.Field()
    """
    Whether the grant is a fixed amount per company, or issued once per license the company holds.
    """

    tier_mode: typing.Optional[BillingTiersMode] = pydantic.Field(default=None)
    """
    How price_tiers apply: volume prices every credit at the rate of the tier the total lands in, graduated prices each tier's own credits at its own rate. Set only when price_tiers is non-empty.
    """

    unit_price: typing.Optional[int] = pydantic.Field(default=None)
    """
    Price per credit in the plan currency's smallest unit. Set only when billing_mode is billed and the credits are priced at one rate.
    """

    unit_price_decimal: typing.Optional[str] = pydantic.Field(default=None)
    """
    Price per credit as a decimal in the plan currency's smallest unit. Set only when billing_mode is billed and the rate is below one cent.
    """

    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
