# This file was auto-generated by Fern from our API Definition.

import typing

BillingPlanCreditGrantResetCadence = typing.Union[
    typing.Literal["daily", "every_6_months", "monthly", "quarterly", "weekly", "yearly"], typing.Any
]
