# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CatalogResponseData(UniversalBaseModel):
    account_id: str
    created_at: dt.datetime
    custom_plan_cta_text: typing.Optional[str] = None
    custom_plan_cta_url: typing.Optional[str] = None
    custom_plan_price_text: typing.Optional[str] = None
    custom_plans_visible: bool
    description: typing.Optional[str] = None
    environment_id: str
    id: str
    is_default: bool
    name: str
    pricing_model: typing.Optional[str] = None
    pricing_url: typing.Optional[str] = None
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
