# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .check_flag_response_data import CheckFlagResponseData
from .company_credit_balance import CompanyCreditBalance
from .credit_spend_policy import CreditSpendPolicy
from .datastream_company_plan import DatastreamCompanyPlan


class CheckFlagsResponseData(UniversalBaseModel):
    credit_balances: typing.Optional[typing.Dict[str, CompanyCreditBalance]] = pydantic.Field(default=None)
    """
    Lease-aware credit balances keyed by credit ID, covering every credit type the company holds a balance in
    """

    credit_spend_policies: typing.List[CreditSpendPolicy] = pydantic.Field()
    """
    Credit spend policies binding the evaluated company and user; empty when none bind. Each response carries the whole set, so replace any previously received set with it. Advisory: the flag values do not reflect them, since a check names no draw amount
    """

    flags: typing.List[CheckFlagResponseData]
    plan: typing.Optional[DatastreamCompanyPlan] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
