# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .company_feature_usage_export_metadata_sort_order_direction import (
    CompanyFeatureUsageExportMetadataSortOrderDirection,
)
from .company_feature_usage_export_metadata_visible_columns_item import (
    CompanyFeatureUsageExportMetadataVisibleColumnsItem,
)


class CompanyFeatureUsageExportMetadata(UniversalBaseModel):
    company_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restrict the export to these Schematic company IDs (starting with 'comp_')
    """

    credit_type_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restrict the export to companies with these billing credit type IDs
    """

    entity_key_definition_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Company key definition IDs to include as columns, one column per definition, mirroring the companies list
    """

    entity_trait_definition_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Company trait definition IDs to include as columns, one column per definition, mirroring the companies list
    """

    feature_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Schematic feature IDs (starting with 'feat_') to include as usage columns; empty means no usage columns
    """

    has_scheduled_downgrade: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Restrict the export to companies that do (or do not) have a scheduled downgrade
    """

    monetized_subscriptions: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Restrict the export to companies with (or without) a monetized subscription
    """

    notification_email_recipient_email_addresses: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Account member emails to notify when the export completes; empty means the artifact is only retrievable via the API
    """

    plan_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Restrict the export to companies on this plan ID (starting with 'plan_')
    """

    plan_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restrict the export to companies on any of these plan IDs
    """

    plan_version_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Restrict the export to companies on this plan version ID
    """

    plan_version_unpublished: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Restrict the export to companies on a plan version that is no longer published
    """

    q: typing.Optional[str] = pydantic.Field(default=None)
    """
    Free-text search over company name and keys
    """

    sort_order_column: typing.Optional[str] = pydantic.Field(default=None)
    """
    Column to sort the exported rows by (e.g. name, created_at, plan); defaults to name
    """

    sort_order_direction: typing.Optional[CompanyFeatureUsageExportMetadataSortOrderDirection] = pydantic.Field(
        default=None
    )
    """
    Direction to sort the exported rows by; defaults to asc
    """

    subscription_statuses: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restrict the export to companies whose subscription has one of these statuses
    """

    subscription_types: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Restrict the export to companies whose subscription has one of these types
    """

    visible_columns: typing.Optional[typing.List[CompanyFeatureUsageExportMetadataVisibleColumnsItem]] = pydantic.Field(
        default=None
    )
    """
    Company columns to include, mirroring the companies list; omit to include the plan column only
    """

    with_entitlement_for: typing.Optional[str] = pydantic.Field(default=None)
    """
    Restrict the export to companies that have an entitlement for this feature ID
    """

    with_subscription: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Restrict the export to companies with a subscription
    """

    without_feature_override_for: typing.Optional[str] = pydantic.Field(default=None)
    """
    Restrict the export to companies without a company-level override for this feature ID
    """

    without_plan: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Restrict the export to companies without a plan
    """

    without_subscription: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Restrict the export to companies without a subscription
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
