# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .feature_response_data import FeatureResponseData


class CompanyUserUsageMetricsResponseData(UniversalBaseModel):
    end_time: dt.datetime = pydantic.Field()
    """
    End of the usage window (exclusive)
    """

    features: typing.List[FeatureResponseData] = pydantic.Field()
    """
    Event-based features the company has user-attributed usage for in the window; a feature with usage but no entitlement is still listed
    """

    has_credits: bool = pydantic.Field()
    """
    Whether the company consumed any credits in the window
    """

    start_time: dt.datetime = pydantic.Field()
    """
    Start of the usage window
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
