# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .user_response_data import UserResponseData


class CompanyUserUsageRowResponseData(UniversalBaseModel):
    last_seen: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the user last used the feature within the window; null for the credits metric, which aggregates balances rather than timestamped events
    """

    share: float = pydantic.Field()
    """
    This row's fraction (0-1) of consumption within the window, including unattributed consumption
    """

    user: typing.Optional[UserResponseData] = pydantic.Field(default=None)
    """
    The user the consumption is attributed to; null for consumption from events sent without a user
    """

    user_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user the consumption is attributed to; null for unattributed consumption
    """

    value: float = pydantic.Field()
    """
    The user's consumption of the metric within the window
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
