# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_collection_method import BillingCollectionMethod
from .billing_provider_type import BillingProviderType
from .proration_behavior import ProrationBehavior


class CompanyBillingProfileResponseData(UniversalBaseModel):
    account_id: str
    billing_customer_id: typing.Optional[str] = None
    collection_method: BillingCollectionMethod
    company_id: str
    created_at: dt.datetime
    days_until_due: typing.Optional[int] = None
    environment_id: str
    id: str
    is_default: bool
    name: typing.Optional[str] = None
    payment_method_id: typing.Optional[str] = None
    proration_behavior: typing.Optional[ProrationBehavior] = None
    provider_type: BillingProviderType
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
