# This file was auto-generated by Fern from our API Definition.

import typing

ComparableOperator = typing.Union[
    typing.Literal["eq", "gt", "gte", "is_empty", "lt", "lte", "not_empty", "ne"], typing.Any
]
