# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .event_body import EventBody
from .event_type import EventType


class CreateEventRequestBody(UniversalBaseModel):
    backfill: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Requires a secret API key, and trusted_client_clock. Import historical data without affecting billing.
    """

    body: typing.Optional[EventBody] = None
    event_type: EventType = pydantic.Field()
    """
    Either 'identify' or 'track'
    """

    idempotency_key: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional client-supplied key. Duplicate events with the same key (scoped to the environment) are dropped for 24h.
    """

    sent_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Optionally provide a timestamp at which the event was sent to Schematic
    """

    trusted_client_clock: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Requires a secret API key and sent_at. Use sent_at as the effective timestamp.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
