# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_credit_expiry_type import BillingCreditExpiryType
from .billing_credit_expiry_unit import BillingCreditExpiryUnit
from .billing_credit_grant_reason import BillingCreditGrantReason
from .billing_credit_grant_zeroed_out_reason import BillingCreditGrantZeroedOutReason
from .billing_credit_ledger_response_data import BillingCreditLedgerResponseData
from .company_ledger_response_data import CompanyLedgerResponseData
from .credit_event_type import CreditEventType
from .feature_ledger_response_data import FeatureLedgerResponseData


class CreditEventLedgerResponseData(UniversalBaseModel):
    amount: float
    auto_topup_log_id: typing.Optional[str] = None
    billing_credit_bundle_id: typing.Optional[str] = None
    billing_credit_id: str
    company: typing.Optional[CompanyLedgerResponseData] = None
    company_id: str
    credit: typing.Optional[BillingCreditLedgerResponseData] = None
    credit_name: str
    environment_id: str
    event_at: dt.datetime
    event_id: str
    event_type: CreditEventType
    expiry_type: typing.Optional[BillingCreditExpiryType] = None
    expiry_unit: typing.Optional[BillingCreditExpiryUnit] = None
    expiry_unit_count: typing.Optional[int] = None
    feature: typing.Optional[FeatureLedgerResponseData] = None
    feature_id: typing.Optional[str] = None
    from_grant_id: typing.Optional[str] = None
    grant_expires_at: typing.Optional[dt.datetime] = None
    grant_id: typing.Optional[str] = None
    grant_quantity: typing.Optional[int] = None
    grant_quantity_remaining: typing.Optional[float] = None
    grant_reason: typing.Optional[BillingCreditGrantReason] = None
    grant_valid_from: typing.Optional[dt.datetime] = None
    plan_id: typing.Optional[str] = None
    quantity_consumed: typing.Optional[float] = None
    quantity_remaining_at_zero_out: typing.Optional[float] = None
    source_id: int
    to_grant_id: typing.Optional[str] = None
    usage_event_id: typing.Optional[str] = None
    zeroed_out_reason: typing.Optional[BillingCreditGrantZeroedOutReason] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
