# This file was auto-generated by Fern from our API Definition.

import typing

CreditUsageReason = typing.Union[
    typing.Literal[
        "lease_hold",
        "lease_release",
        "manual_adjustment",
        "reconciliation",
        "reservation_hold",
        "reservation_release",
        "track",
    ],
    typing.Any,
]
