# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CreditReservationResponseData(UniversalBaseModel):
    company_id: str
    created_at: dt.datetime
    credit_type_id: str
    expires_at: dt.datetime = pydantic.Field()
    """
    When the unspent hold is refunded if no track event settles it
    """

    id: str
    released_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When the reservation was settled, released, or expired; null while the hold is open
    """

    reserved_amount: float = pydantic.Field()
    """
    Credits held from the company's balance for the operation
    """

    settled_amount: float = pydantic.Field()
    """
    Credits the settling track event recorded against the hold; zero until settled. May exceed reserved_amount, in which case the overage was debited from the balance, up to the overdraft limit when one is set
    """

    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
