# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .credit_spend_policy_scope import CreditSpendPolicyScope


class CreditSpendPolicyResponseData(UniversalBaseModel):
    billing_credit_id: str
    company_id: typing.Optional[str] = None
    created_at: dt.datetime
    id: str
    label: typing.Optional[str] = None
    max_per_draw: typing.Optional[float] = None
    scope_type: CreditSpendPolicyScope
    updated_at: dt.datetime
    user_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
