# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .credits_auto_topup_company_summary import CreditsAutoTopupCompanySummary
from .credits_auto_topup_credit_summary import CreditsAutoTopupCreditSummary


class CreditsAutoTopupRetryFailure(UniversalBaseModel):
    company: typing.Optional[CreditsAutoTopupCompanySummary] = None
    consecutive_failures: int
    credit: typing.Optional[CreditsAutoTopupCreditSummary] = None
    last_error_message: typing.Optional[str] = None
    stripe_error_code: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
