# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .custom_plan_activation_strategy import CustomPlanActivationStrategy
from .custom_plan_billing_status import CustomPlanBillingStatus


class CustomPlanBillingResponseData(UniversalBaseModel):
    activation_strategy: CustomPlanActivationStrategy
    company_id: str
    created_at: dt.datetime
    days_until_due: int
    id: str
    paid_at: typing.Optional[dt.datetime] = None
    plan_id: str
    published_at: typing.Optional[dt.datetime] = None
    status: CustomPlanBillingStatus
    stripe_invoice_url: typing.Optional[str] = None
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
