# This file was auto-generated by Fern from our API Definition.

import typing

EventExportMetadataEventTypesItem = typing.Union[
    typing.Literal["flag_check", "identify", "inference", "track"], typing.Any
]
