# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .feature_type import FeatureType
from .limit_time_series_point_response_data import LimitTimeSeriesPointResponseData
from .usage_time_series_point_response_data import UsageTimeSeriesPointResponseData


class FeatureUsageTimeSeriesResponseData(UniversalBaseModel):
    feature_id: str
    feature_type: FeatureType
    limits: typing.List[LimitTimeSeriesPointResponseData]
    period_type: typing.Optional[str] = None
    usage_points: typing.List[UsageTimeSeriesPointResponseData]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
