# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .credit_usage import CreditUsage
from .feature_view import FeatureView


class FeatureUsageLegacyResponseData(UniversalBaseModel):
    allocation: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="Allocation")] = None
    credit_usage: typing_extensions.Annotated[typing.Optional[CreditUsage], FieldMetadata(alias="CreditUsage")] = None
    entitlement: typing_extensions.Annotated[str, FieldMetadata(alias="Entitlement")]
    feature: typing_extensions.Annotated[typing.Optional[FeatureView], FieldMetadata(alias="Feature")] = None
    metric_reset_at: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="MetricResetAt")] = (
        None
    )
    usage: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="Usage")] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
