# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class FeatureUsageHistoryResponseData(UniversalBaseModel):
    company_id: str = pydantic.Field()
    """
    Companies are identified by ID only. To report against your own identifiers, resolve them once via the companies API and cache the mapping; keys are not repeated on every row.
    """

    event_subtype: str
    feature_id: str
    period_end: dt.datetime = pydantic.Field()
    """
    Exclusive end of the period this usage covers
    """

    period_start: dt.datetime = pydantic.Field()
    """
    Inclusive start of the period this usage covers
    """

    usage: int = pydantic.Field()
    """
    Usage recorded within this period; an incremental total, not a running one
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
