# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entitlement_value_type import EntitlementValueType
from .metric_period import MetricPeriod
from .metric_period_month_reset import MetricPeriodMonthReset
from .warning_tier import WarningTier


class FeatureEntitlement(UniversalBaseModel):
    allocation: typing.Optional[int] = pydantic.Field(default=None)
    """
    If the company has a numeric entitlement for this feature, the allocated amount
    """

    consumption_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the credit cost per unit of usage
    """

    credit_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the ID of the credit
    """

    credit_remaining: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the credit available to fund new consumption or a new lease hold — open lease holds are excluded. Clients that hold a lease should gate on this plus their own unspent hold; clients with no lease awareness should use credit_settled instead
    """

    credit_reserved: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the unspent amount held by an open credit lease. Returns to credit_remaining when the lease is released
    """

    credit_settled: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the balance net of actual consumption, unaffected by open lease holds (credit_remaining plus credit_reserved). The number to display to end users
    """

    credit_total: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the total credit amount
    """

    credit_used: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the amount of credit used
    """

    event_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    If the feature is event-based, the name of the event tracked for usage
    """

    event_subtype: typing.Optional[str] = pydantic.Field(default=None)
    """
    For event-based or credit-metered feature entitlements, the event subtype whose usage is tracked
    """

    feature_id: str = pydantic.Field()
    """
    The ID of the feature
    """

    feature_key: str = pydantic.Field()
    """
    The key of the flag associated with the feature
    """

    metric_period: typing.Optional[MetricPeriod] = pydantic.Field(default=None)
    """
    For event-based feature entitlements, the period over which usage is tracked
    """

    metric_reset_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    For event-based feature entitlements, when the usage period will reset
    """

    month_reset: typing.Optional[MetricPeriodMonthReset] = pydantic.Field(default=None)
    """
    For event-based feature entitlements that have a monthly period, whether that monthly reset is based on the calendar month or a billing cycle
    """

    soft_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    For usage-based pricing, the soft limit for overage charges or the next tier boundary
    """

    usage: typing.Optional[int] = pydantic.Field(default=None)
    """
    If the company has a numeric entitlement for this feature, the current usage amount
    """

    value_type: EntitlementValueType = pydantic.Field()
    """
    The type of the entitlement value
    """

    warning_tiers: typing.Optional[typing.List[WarningTier]] = pydantic.Field(default=None)
    """
    Customer-defined usage warning thresholds configured on this entitlement
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
