# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .onboarding_milestone_view import OnboardingMilestoneView
from .onboarding_path import OnboardingPath
from .onboarding_requirement import OnboardingRequirement
from .onboarding_requirement_view import OnboardingRequirementView
from .onboarding_stripe_import import OnboardingStripeImport
from .onboarding_track import OnboardingTrack


class GetOnboardingStateResp(UniversalBaseModel):
    agent_connected_at: typing.Optional[dt.datetime] = None
    country: typing.Optional[str] = None
    dismissed_at: typing.Optional[dt.datetime] = None
    environment_id: typing.Optional[str] = None
    milestones: typing.List[OnboardingMilestoneView]
    path: typing.Optional[OnboardingPath] = None
    pricing_page_url: typing.Optional[str] = None
    requirements: typing.List[OnboardingRequirementView]
    stripe_import: typing.Optional[OnboardingStripeImport] = None
    suggested_next: typing.List[OnboardingRequirement]
    track: typing.Optional[OnboardingTrack] = None
    website_url: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
