# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class IntegrationConfig_Clerk(UniversalBaseModel):
    type: typing.Literal["clerk"] = "clerk"
    first_events_received: typing.Optional[bool] = None
    webhook_url: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class IntegrationConfig_Orb(UniversalBaseModel):
    type: typing.Literal["orb"] = "orb"
    external_customer_id_key: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class IntegrationConfig_Stripe(UniversalBaseModel):
    type: typing.Literal["stripe"] = "stripe"
    account_id: typing.Optional[str] = None
    account_name: typing.Optional[str] = None
    company_update_only: typing.Optional[bool] = None
    is_sandbox: bool
    live_mode: bool
    onboard_url: typing.Optional[str] = None
    version: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


IntegrationConfig = typing_extensions.Annotated[
    typing.Union[IntegrationConfig_Clerk, IntegrationConfig_Orb, IntegrationConfig_Stripe],
    pydantic.Field(discriminator="type"),
]
