# This file was auto-generated by Fern from our API Definition.

import typing

MigrationErrorCode = typing.Union[
    typing.Literal[
        "ambiguous_subscription_item",
        "multiple_subscriptions",
        "no_price_for_interval",
        "not_on_origin_version",
        "operation_item_not_found",
        "permanent_config",
        "permanent_decline",
        "transient_decline",
        "transient_infra",
        "transient_stripe",
        "unknown",
        "would_leave_empty_subscription",
    ],
    typing.Any,
]
