# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .onboarding_requirement import OnboardingRequirement
from .onboarding_requirement_status import OnboardingRequirementStatus


class OnboardingRequirementView(UniversalBaseModel):
    blocked_by: typing.Optional[typing.List[OnboardingRequirement]] = None
    id: OnboardingRequirement
    reached_at: typing.Optional[dt.datetime] = None
    satisfied_by: typing.Optional[str] = None
    status: OnboardingRequirementStatus

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
