# This file was auto-generated by Fern from our API Definition.

import typing

OnboardingRequirement = typing.Union[
    typing.Literal[
        "connect_agent",
        "connect_billing",
        "create_api_key",
        "first_flag_check",
        "generate_roadmap",
        "import_companies",
        "model_packaging",
        "send_events",
    ],
    typing.Any,
]
