# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .plan_version_migration_status import PlanVersionMigrationStatus
from .plan_version_migration_strategy import PlanVersionMigrationStrategy


class PlanVersionMigrationResponseData(UniversalBaseModel):
    completed_at: typing.Optional[dt.datetime] = None
    completed_companies: int
    created_at: dt.datetime
    error: typing.Optional[str] = None
    failed_companies: int
    id: str
    plan_id: str
    plan_version_id_from: typing.Optional[str] = None
    plan_version_id_to: str
    skipped_companies: int
    started_at: typing.Optional[dt.datetime] = None
    status: PlanVersionMigrationStatus
    strategy: PlanVersionMigrationStrategy
    total_companies: int
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
