# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_price_response_data import BillingPriceResponseData
from .billing_product_detail_response_data import BillingProductDetailResponseData
from .charge_type import ChargeType
from .custom_plan_config import CustomPlanConfig
from .feature_detail_response_data import FeatureDetailResponseData
from .plan_controlled_by_type import PlanControlledByType
from .plan_credit_grant_view import PlanCreditGrantView
from .plan_entitlement_response_data import PlanEntitlementResponseData
from .plan_type import PlanType
from .plan_version_response_data import PlanVersionResponseData


class PlanViewPublicResponseData(UniversalBaseModel):
    active_version: typing.Optional[PlanVersionResponseData] = None
    audience_type: typing.Optional[str] = None
    billing_product: typing.Optional[BillingProductDetailResponseData] = None
    charge_type: ChargeType
    company_count: int
    compatible_plan_ids: typing.List[str]
    controlled_by: PlanControlledByType
    created_at: dt.datetime
    custom: bool
    custom_plan_config: typing.Optional[CustomPlanConfig] = None
    description: str
    draft_version: typing.Optional[PlanVersionResponseData] = None
    entitlements: typing.List[PlanEntitlementResponseData]
    features: typing.List[FeatureDetailResponseData]
    icon: str
    id: str
    included_credit_grants: typing.List[PlanCreditGrantView]
    is_custom: bool
    is_default: bool
    is_free: bool
    is_trialable: bool
    monthly_price: typing.Optional[BillingPriceResponseData] = None
    name: str
    one_time_price: typing.Optional[BillingPriceResponseData] = None
    plan_type: PlanType
    trial_days: typing.Optional[int] = None
    updated_at: dt.datetime
    versions: typing.List[PlanVersionResponseData]
    yearly_price: typing.Optional[BillingPriceResponseData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
