# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PlanVersionMigrationPreviewCompanyResponseData(UniversalBaseModel):
    company_id: str
    has_billing_changes: bool
    has_custom_pricing: bool
    note: typing.Optional[str] = None
    plan_version_id_from: typing.Optional[str] = None
    will_update_subscription: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
