# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_linked_resource_response_data import BillingLinkedResourceResponseData
from .billing_plan_credit_grant_response_data import BillingPlanCreditGrantResponseData
from .billing_price_response_data import BillingPriceResponseData
from .billing_product_detail_response_data import BillingProductDetailResponseData
from .billing_provider_type import BillingProviderType
from .charge_type import ChargeType
from .feature_in_plan_response_data import FeatureInPlanResponseData
from .plan_currency_prices_response_data import PlanCurrencyPricesResponseData
from .plan_icon import PlanIcon
from .plan_type import PlanType
from .plan_version_response_data import PlanVersionResponseData


class PlanDetailResponseData(UniversalBaseModel):
    active_version: typing.Optional[PlanVersionResponseData] = None
    audience_type: typing.Optional[str] = None
    billing_linked_resource: typing.Optional[BillingLinkedResourceResponseData] = None
    billing_product: typing.Optional[BillingProductDetailResponseData] = None
    charge_type: ChargeType
    company_count: int
    company_id: typing.Optional[str] = None
    company_name: typing.Optional[str] = None
    controlled_by: BillingProviderType
    copied_from_plan_id: typing.Optional[str] = None
    created_at: dt.datetime
    currency_prices: typing.List[PlanCurrencyPricesResponseData]
    description: str
    draft_version: typing.Optional[PlanVersionResponseData] = None
    features: typing.List[FeatureInPlanResponseData]
    icon: PlanIcon
    id: str
    included_credit_grants: typing.Optional[typing.List[BillingPlanCreditGrantResponseData]] = None
    is_default: bool
    is_free: bool
    is_trialable: bool
    monthly_price: typing.Optional[BillingPriceResponseData] = None
    name: str
    one_time_price: typing.Optional[BillingPriceResponseData] = None
    plan_type: PlanType
    trial_days: typing.Optional[int] = None
    updated_at: dt.datetime
    versions: typing.List[PlanVersionResponseData]
    yearly_price: typing.Optional[BillingPriceResponseData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
