# This file was auto-generated by Fern from our API Definition.

import typing

PlanIcon = typing.Union[
    typing.Literal[
        "amber",
        "blue",
        "blueGray",
        "blueGreen",
        "cyan",
        "emerald",
        "fuchsia",
        "gray",
        "green",
        "indigo",
        "lightBlue",
        "lime",
        "orange",
        "pink",
        "purple",
        "red",
        "redOrange",
        "rose",
        "sky",
        "slate",
        "teal",
        "trueGray",
        "violet",
        "warmGray",
        "yellow",
    ],
    typing.Any,
]
