# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .migration_error_code import MigrationErrorCode
from .plan_version_company_migration_status import PlanVersionCompanyMigrationStatus


class PlanVersionCompanyMigrationResponseData(UniversalBaseModel):
    company_id: str
    company_name: str
    completed_at: typing.Optional[dt.datetime] = None
    created_at: dt.datetime
    error: typing.Optional[str] = None
    error_code: typing.Optional[MigrationErrorCode] = None
    id: str
    migration_id: str
    plan_version_id_from: typing.Optional[str] = None
    scheduled_for: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When this company is expected to migrate, for a migration scheduled at the end of the billing period: the end of the company's current billing period. Only set while both the company and the migration are still pending. A value at or before the time of the request means the company has no active subscription and migrates as soon as processing runs. Null means no upcoming renewal could be determined from the company's current billing status (for example, a past-due subscription or one set to cancel); it does not mean the company will never migrate.
    """

    started_at: typing.Optional[dt.datetime] = None
    status: PlanVersionCompanyMigrationStatus
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
