# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .plan_version_company_migration_status import PlanVersionCompanyMigrationStatus


class PlanVersionCompanyMigrationResponseData(UniversalBaseModel):
    company_id: str
    company_name: str
    completed_at: typing.Optional[dt.datetime] = None
    created_at: dt.datetime
    error: typing.Optional[str] = None
    id: str
    migration_id: str
    plan_version_id_from: typing.Optional[str] = None
    started_at: typing.Optional[dt.datetime] = None
    status: PlanVersionCompanyMigrationStatus
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
