# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_plan_credit_grant_response_data import BillingPlanCreditGrantResponseData
from .billing_product_plan_response_data import BillingProductPlanResponseData
from .plan_entitlement_response_data import PlanEntitlementResponseData
from .plan_response_data import PlanResponseData
from .plan_trait_response_data import PlanTraitResponseData


class PlanBundleResponseData(UniversalBaseModel):
    billing_product: typing.Optional[BillingProductPlanResponseData] = None
    credit_grants: typing.Optional[typing.List[BillingPlanCreditGrantResponseData]] = None
    entitlements: typing.Optional[typing.List[PlanEntitlementResponseData]] = None
    plan: typing.Optional[PlanResponseData] = None
    traits: typing.Optional[typing.List[PlanTraitResponseData]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
