# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_arrears_anchor import BillingArrearsAnchor
from .billing_arrears_cadence import BillingArrearsCadence
from .billing_credit_response_data import BillingCreditResponseData
from .billing_linked_resource_response_data import BillingLinkedResourceResponseData
from .billing_price_view import BillingPriceView
from .billing_product_response_data import BillingProductResponseData
from .entitlement_currency_prices_response_data import EntitlementCurrencyPricesResponseData
from .entitlement_price_behavior import EntitlementPriceBehavior
from .entitlement_value_type import EntitlementValueType
from .entity_trait_definition_response_data import EntityTraitDefinitionResponseData
from .feature_response_data import FeatureResponseData
from .metric_period import MetricPeriod
from .metric_period_month_reset import MetricPeriodMonthReset
from .plan_response_data import PlanResponseData
from .warning_tier_response_data import WarningTierResponseData


class PlanEntitlementResponseData(UniversalBaseModel):
    billing_linked_resource: typing.Optional[BillingLinkedResourceResponseData] = None
    billing_threshold: typing.Optional[int] = None
    consumption_rate: typing.Optional[float] = None
    created_at: dt.datetime
    currency_prices: typing.List[EntitlementCurrencyPricesResponseData]
    environment_id: str
    feature: typing.Optional[FeatureResponseData] = None
    feature_id: str
    id: str
    metered_monthly_price: typing.Optional[BillingPriceView] = None
    metered_quarterly_price: typing.Optional[BillingPriceView] = None
    metered_yearly_price: typing.Optional[BillingPriceView] = None
    metric_period: typing.Optional[MetricPeriod] = None
    metric_period_month_reset: typing.Optional[MetricPeriodMonthReset] = None
    overage_billing_cadence: typing.Optional[BillingArrearsCadence] = pydantic.Field(default=None)
    """
    How often overage charges are assessed and invoiced. Null or end_of_billing_period means the billing provider aggregates usage over the subscription's own period and bills it at period end. Monthly and quarterly mean Schematic assesses the overage each month or quarter and bills it on its own invoice. Only applies to overage price behavior.
    """

    overage_invoice_anchor: typing.Optional[BillingArrearsAnchor] = pydantic.Field(default=None)
    """
    Which boundary closes a monthly or quarterly overage window: the subscription's own recurrence (billing_period_start) or the calendar month (month_end), which for a quarterly window means calendar quarters. Only meaningful when overage_billing_cadence is monthly or quarterly.
    """

    plan: typing.Optional[PlanResponseData] = None
    plan_id: str
    price_behavior: typing.Optional[EntitlementPriceBehavior] = None
    rule_id: str
    rule_id_usage_exceeded: typing.Optional[str] = None
    soft_limit: typing.Optional[int] = None
    updated_at: dt.datetime
    usage_based_product: typing.Optional[BillingProductResponseData] = None
    usage_quantity: typing.Optional[int] = pydantic.Field(default=None)
    """
    The committed unit quantity for this entitlement. For custom plans this is the quantity the company is contractually committed to; for standard plans it is the quantity pre-filled when subscribing. Only applies to pay-in-advance entitlements. Note: this is not yet enforced/auto-provisioned as a true default — it is currently stored for downstream billing use.
    """

    value_bool: typing.Optional[bool] = None
    value_credit: typing.Optional[BillingCreditResponseData] = None
    value_numeric: typing.Optional[int] = None
    value_trait: typing.Optional[EntityTraitDefinitionResponseData] = None
    value_trait_id: typing.Optional[str] = None
    value_type: EntitlementValueType
    warning_tiers: typing.List[WarningTierResponseData]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
