# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PreflightEventUsageRequestBody(UniversalBaseModel):
    event_subtype: str = pydantic.Field()
    """
    The event subtype the usage would be recorded under
    """

    quantity: int = pydantic.Field()
    """
    How many units of the event subtype the action would record. Zero has no effect
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
