# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .compatible_plans import CompatiblePlans
from .component_capabilities import ComponentCapabilities
from .component_display_settings import ComponentDisplaySettings
from .plan_view_public_response_data import PlanViewPublicResponseData


class PublicPlansResponseData(UniversalBaseModel):
    active_add_ons: typing.List[PlanViewPublicResponseData]
    active_plans: typing.List[PlanViewPublicResponseData]
    add_on_compatibilities: typing.List[CompatiblePlans]
    capabilities: typing.Optional[ComponentCapabilities] = None
    display_settings: ComponentDisplaySettings
    show_as_monthly_prices: bool
    show_credits: bool
    show_period_toggle: bool
    show_zero_price_as_free: bool

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
