# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .rulesengine_entitlement_value_type import RulesengineEntitlementValueType
from .rulesengine_metric_period import RulesengineMetricPeriod
from .rulesengine_metric_period_month_reset import RulesengineMetricPeriodMonthReset


class RulesengineFeatureEntitlement(UniversalBaseModel):
    allocation: typing.Optional[int] = pydantic.Field(default=None)
    """
    If the company has a numeric entitlement for this feature, the allocated amount
    """

    credit_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the ID of the credit
    """

    credit_remaining: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the remaining credit amount
    """

    credit_total: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the total credit amount
    """

    credit_used: typing.Optional[float] = pydantic.Field(default=None)
    """
    If the company has a credit-based entitlement for this feature, the amount of credit used
    """

    event_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    If the feature is event-based, the name of the event tracked for usage
    """

    feature_id: str = pydantic.Field()
    """
    The ID of the feature
    """

    feature_key: str = pydantic.Field()
    """
    The key of the flag associated with the feature
    """

    metric_period: typing.Optional[RulesengineMetricPeriod] = pydantic.Field(default=None)
    """
    For event-based feature entitlements, the period over which usage is tracked
    """

    metric_reset_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    For event-based feature entitlements, when the usage period will reset
    """

    month_reset: typing.Optional[RulesengineMetricPeriodMonthReset] = pydantic.Field(default=None)
    """
    For event-based feature entitlements that have a monthly period, whether that monthly reset is based on the calendar month or a billing cycle
    """

    soft_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    For usage-based pricing, the soft limit for overage charges or the next tier boundary
    """

    usage: typing.Optional[int] = pydantic.Field(default=None)
    """
    If the company has a numeric entitlement for this feature, the current usage amount
    """

    value_type: RulesengineEntitlementValueType = pydantic.Field()
    """
    The type of the entitlement value
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
