# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .comparable_operator import ComparableOperator
from .condition_type import ConditionType
from .entity_trait_definition_response_data import EntityTraitDefinitionResponseData
from .entity_type import EntityType
from .metric_period import MetricPeriod
from .metric_period_month_reset import MetricPeriodMonthReset
from .preview_object_response_data import PreviewObjectResponseData


class RuleConditionDetailResponseData(UniversalBaseModel):
    comparison_trait: typing.Optional[EntityTraitDefinitionResponseData] = None
    comparison_trait_id: typing.Optional[str] = None
    condition_group_id: typing.Optional[str] = None
    condition_type: ConditionType
    created_at: dt.datetime
    environment_id: str
    event_subtype: typing.Optional[str] = None
    flag_id: typing.Optional[str] = None
    id: str
    metric_period: typing.Optional[MetricPeriod] = None
    metric_period_month_reset: typing.Optional[MetricPeriodMonthReset] = None
    metric_value: typing.Optional[int] = None
    operator: ComparableOperator
    resource_ids: typing.List[str]
    resources: typing.List[PreviewObjectResponseData]
    rule_id: str
    trait: typing.Optional[EntityTraitDefinitionResponseData] = None
    trait_entity_type: typing.Optional[EntityType] = None
    trait_id: typing.Optional[str] = None
    trait_value: str
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
