# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class RulesengineWarningTier(UniversalBaseModel):
    key: str = pydantic.Field()
    """
    A customer-defined identifier for the warning tier
    """

    value: int = pydantic.Field()
    """
    The warning threshold, in the entitlement's usage units
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
