# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .rulesengine_credit_spend_policy_scope import RulesengineCreditSpendPolicyScope
from .rulesengine_credit_spend_window import RulesengineCreditSpendWindow


class RulesengineCreditSpendPolicy(UniversalBaseModel):
    consumed: typing.Optional[float] = pydantic.Field(default=None)
    """
    How much of the limit is already spent in the current period
    """

    credit_id: str = pydantic.Field()
    """
    The credit the policy limits
    """

    id: str = pydantic.Field()
    """
    The ID of the policy
    """

    kind: str = pydantic.Field()
    """
    How the limit is applied
    """

    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name the account gave the policy
    """

    limit: float = pydantic.Field()
    """
    The ceiling, in credits
    """

    resets_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    For a windowed limit, when the current period ends and consumed no longer applies
    """

    scope: RulesengineCreditSpendPolicyScope = pydantic.Field()
    """
    Whether the policy limits the company or one user
    """

    window: typing.Optional[RulesengineCreditSpendWindow] = pydantic.Field(default=None)
    """
    For a windowed limit, the period it accumulates over
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
