# This file was auto-generated by Fern from our API Definition.

import typing

RulesengineRuleType = typing.Union[
    typing.Literal[
        "company_override",
        "company_override_usage_exceeded",
        "default",
        "global_override",
        "plan_entitlement",
        "plan_entitlement_usage_exceeded",
        "standard",
    ],
    typing.Any,
]
