# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .scheduled_checkout_status import ScheduledCheckoutStatus


class ScheduledCheckoutResponseData(UniversalBaseModel):
    actor_type: str
    company_id: str
    completed_at: typing.Optional[dt.datetime] = None
    created_at: dt.datetime
    error_message: typing.Optional[str] = None
    execute_after: dt.datetime
    from_plan_id: str
    id: str
    scheduled_interval: typing.Optional[str] = None
    scheduled_price: typing.Optional[int] = None
    started_at: typing.Optional[dt.datetime] = None
    status: ScheduledCheckoutStatus
    to_plan_id: str
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
