# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .slack_connect_invite_status import SlackConnectInviteStatus


class SlackConnectInviteView(UniversalBaseModel):
    can_resend_at: typing.Optional[dt.datetime] = None
    email: str
    sent_at: dt.datetime
    status: SlackConnectInviteStatus

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
