# This file was auto-generated by Fern from our API Definition.

import typing

SlackConnectInviteStatus = typing.Union[
    typing.Literal["accepted", "declined", "dismissed", "expired", "pending"], typing.Any
]
