# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class StripeIntegrationConfig(UniversalBaseModel):
    account_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Connected Stripe account ID (acct_*)
    """

    account_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Display name of the connected Stripe account
    """

    claimable_sandbox_expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    When Stripe deletes the sandbox if nobody claims it, 60 days from creation; absent on sandboxes created before it was recorded
    """

    claimable_sandbox_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stripe claimable sandbox this connection was provisioned from; absent for an OAuth connect
    """

    claimable_sandbox_status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Stripe's claim status for the sandbox: unclaimed, claimed, or live
    """

    company_update_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When importing Stripe customers, only update existing companies, do not create new companies
    """

    is_sandbox: bool = pydantic.Field()
    """
    Whether the integration is connected to a Stripe sandbox account
    """

    live_mode: bool = pydantic.Field()
    """
    Whether the integration is connected to a live Stripe account
    """

    onboard_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    Onboarding URL returned during the v2 (Connect) install flow before activation
    """

    return_to: typing.Optional[str] = pydantic.Field(default=None)
    """
    App location that started the connect flow; the OAuth callback redirects back there on success
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
