# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .integration_install_response_data import IntegrationInstallResponseData
from .stripe_sandbox_keys_response_data import StripeSandboxKeysResponseData


class StripeSandboxInstallResponseData(UniversalBaseModel):
    api_keys: typing.Optional[StripeSandboxKeysResponseData] = None
    claim_url: str
    claim_url_expires_at: typing.Optional[dt.datetime] = None
    expires_at: typing.Optional[dt.datetime] = None
    install: IntegrationInstallResponseData
    sandbox_id: str
    stripe_account_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
