# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_arrears_anchor import BillingArrearsAnchor
from .billing_arrears_cadence import BillingArrearsCadence
from .billing_credit_auto_topup_availability import BillingCreditAutoTopupAvailability
from .billing_credit_expiry_type import BillingCreditExpiryType
from .billing_credit_expiry_unit import BillingCreditExpiryUnit
from .billing_plan_credit_grant_billing_mode import BillingPlanCreditGrantBillingMode
from .billing_plan_credit_grant_reset_cadence import BillingPlanCreditGrantResetCadence
from .billing_plan_credit_grant_reset_start import BillingPlanCreditGrantResetStart
from .billing_plan_credit_grant_reset_type import BillingPlanCreditGrantResetType
from .billing_tiers_mode import BillingTiersMode
from .credit_auto_topup_amount_type import CreditAutoTopupAmountType
from .credit_grant_price_tier_request_body import CreditGrantPriceTierRequestBody
from .plan_credit_grant_scaling import PlanCreditGrantScaling


class UpdateBillingPlanCreditGrantRequestBody(UniversalBaseModel):
    apply_to_existing: typing.Optional[bool] = None
    arrears_anchor: typing.Optional[BillingArrearsAnchor] = pydantic.Field(default=None)
    """
    Which boundary closes a monthly arrears window: the subscription's own recurrence (billing_period_start) or the calendar month (month_end). Only applies when arrears_cadence is monthly; defaults to billing_period_start. Send null to fall back to the default.
    """

    arrears_cadence: typing.Optional[BillingArrearsCadence] = pydantic.Field(default=None)
    """
    How often postpaid charges are closed and invoiced: end_of_billing_period (the default) or monthly. Quarterly is not available for postpaid charges. Send null to fall back to the default.
    """

    auto_topup_amount: typing.Optional[int] = None
    auto_topup_amount_type: typing.Optional[CreditAutoTopupAmountType] = None
    auto_topup_availability: typing.Optional[BillingCreditAutoTopupAvailability] = None
    auto_topup_enabled: typing.Optional[bool] = None
    auto_topup_expiry_type: typing.Optional[BillingCreditExpiryType] = None
    auto_topup_expiry_unit: typing.Optional[BillingCreditExpiryUnit] = None
    auto_topup_expiry_unit_count: typing.Optional[int] = None
    auto_topup_self_service: typing.Optional[bool] = None
    auto_topup_threshold_credits: typing.Optional[int] = None
    auto_topup_threshold_percent: typing.Optional[int] = None
    billing_mode: typing.Optional[BillingPlanCreditGrantBillingMode] = pydantic.Field(default=None)
    """
    Whether the credits are included in the plan price (granted) or billed as their own subscription line at a price per credit (billed). Billed is only available on custom plans.
    """

    can_buy_bundles: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Deprecated: use compatible_plan_ids on credit bundles instead. Still accepted; writes through to the credit's bundle compatibility.
    """

    company_credit_amount: typing.Optional[int] = pydantic.Field(default=None)
    """
    Credits granted once per company on top of the per-license amount. Only valid when the grant scales per license.
    """

    credit_amount: typing.Optional[int] = None
    expiry_type: typing.Optional[BillingCreditExpiryType] = None
    expiry_unit: typing.Optional[BillingCreditExpiryUnit] = None
    expiry_unit_count: typing.Optional[int] = None
    license_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The license whose quantity scales this grant. Cleared when the grant moves off per-license scaling.
    """

    overdraft_limit: typing.Optional[float] = pydantic.Field(default=None)
    """
    Optional limit on how far the balance may go below zero, in credits. It is a floor on the balance rather than an allowance per invoice window: the balance may run down to minus this figure, and beyond it the flag check denies the same way an exhausted balance does with postpaid off. Nothing resets when an invoice window rolls, so a company that reaches the limit stays denied until a new grant lands or the negative balance is settled. Send null to remove the limit.
    """

    postpaid_enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether consumption may continue past a zero balance. When false (the default) the flag check denies once the balance is exhausted, which is the existing behavior. When true, consumption continues and accrues at postpaid_rate_per_unit, settled on arrears_cadence. Intended for invoice-billed customers on net terms, who have no card for auto top-up to charge.
    """

    postpaid_rate_per_unit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Amount charged per credit consumed past a zero balance, in the currency's minor unit. Send null to clear it, in which case an enabled grant falls back to the credit's own cost basis (price_per_unit).
    """

    postpaid_rate_per_unit_decimal: typing.Optional[str] = pydantic.Field(default=None)
    """
    Decimal string form of postpaid_rate_per_unit, for rates finer than one minor unit (for example 0.0002). Takes precedence over postpaid_rate_per_unit when both are set, matching how the credit's own price_per_unit_decimal behaves. Send null to clear it.
    """

    price_tiers: typing.Optional[typing.List[CreditGrantPriceTierRequestBody]] = pydantic.Field(default=None)
    """
    Tier table pricing the credits on this grant, cheapest bound first, the last tier unbounded. Sending it moves the grant off one rate per credit. Requires tier_mode.
    """

    reset_cadence: BillingPlanCreditGrantResetCadence
    reset_start: BillingPlanCreditGrantResetStart
    reset_type: typing.Optional[BillingPlanCreditGrantResetType] = None
    rollover_percentage: typing.Optional[int] = pydantic.Field(default=None)
    """
    Percentage of unused credits that carry over when this grant resets. Only applies when reset_type is plan_period. Rolled-over credits expire at the next reset and are not rolled again.
    """

    scaling: typing.Optional[PlanCreditGrantScaling] = pydantic.Field(default=None)
    """
    Whether the grant is a fixed amount per company, or issued once per license the company holds. Changing this re-issues the credits companies already hold for this grant.
    """

    tier_mode: typing.Optional[BillingTiersMode] = pydantic.Field(default=None)
    """
    How price_tiers apply: volume prices every credit at the rate of the tier the total lands in, graduated prices each tier's own credits at its own rate. Required with price_tiers.
    """

    unit_price: typing.Optional[int] = pydantic.Field(default=None)
    """
    Price per credit in the plan currency's smallest unit. Required when billing_mode is billed, unless unit_price_decimal or price_tiers is set. Sending it moves a tiered grant back to one rate per credit.
    """

    unit_price_decimal: typing.Optional[str] = pydantic.Field(default=None)
    """
    Price per credit as a decimal in the plan currency's smallest unit, for prices below one cent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
