# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .charge_type import ChargeType


class UpsertBillingProductRequestBody(UniversalBaseModel):
    billing_product_id: typing.Optional[str] = None
    charge_type: ChargeType
    currency: typing.Optional[str] = None
    is_trialable: bool
    monthly_price: typing.Optional[int] = None
    monthly_price_id: typing.Optional[str] = None
    one_time_price: typing.Optional[int] = None
    one_time_price_id: typing.Optional[str] = None
    trial_days: typing.Optional[int] = None
    yearly_price: typing.Optional[int] = None
    yearly_price_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
