# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .company_response_data import CompanyResponseData
from .plan_snapshot_view import PlanSnapshotView


class WebScheduledDowngradeWebhookOutput(UniversalBaseModel):
    company: typing.Optional[CompanyResponseData] = None
    execute_after: dt.datetime
    from_plan: typing.Optional[PlanSnapshotView] = None
    id: str
    scheduled_interval: typing.Optional[str] = None
    scheduled_price: typing.Optional[int] = None
    to_plan: typing.Optional[PlanSnapshotView] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
