# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .actor_type import ActorType
from .environment_response_data import EnvironmentResponseData


class WhoAmIResponseData(UniversalBaseModel):
    account_id: str
    account_name: str
    actor_type: ActorType
    api_key_id: typing.Optional[str] = None
    environment_id: typing.Optional[str] = None
    environments: typing.List[EnvironmentResponseData]
    stripe_user_id: typing.Optional[str] = None
    user_id: typing.Optional[str] = None
    user_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
