# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.company_billing_entity_response_data import CompanyBillingEntityResponseData
from .get_company_billing_entity_params import GetCompanyBillingEntityParams


class GetCompanyBillingEntityResponse(UniversalBaseModel):
    data: typing.List[CompanyBillingEntityResponseData]
    params: GetCompanyBillingEntityParams = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
