# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.otlp_environment_settings_response_data import OtlpEnvironmentSettingsResponseData


class GetOtlpEnvironmentSettingsResponse(UniversalBaseModel):
    data: OtlpEnvironmentSettingsResponseData
    params: typing.Dict[str, typing.Any] = pydantic.Field()
    """
    Input parameters
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
