# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .get_activity_params import GetActivityParams
    from .get_activity_response import GetActivityResponse
    from .get_environment_feature_usage_time_series_params import GetEnvironmentFeatureUsageTimeSeriesParams
    from .get_environment_feature_usage_time_series_response import GetEnvironmentFeatureUsageTimeSeriesResponse
    from .get_environment_trait_usage_time_series_params import GetEnvironmentTraitUsageTimeSeriesParams
    from .get_environment_trait_usage_time_series_response import GetEnvironmentTraitUsageTimeSeriesResponse
    from .get_plan_growth_params import GetPlanGrowthParams
    from .get_plan_growth_response import GetPlanGrowthResponse
    from .get_summary_response import GetSummaryResponse
    from .get_top_features_by_usage_params import GetTopFeaturesByUsageParams
    from .get_top_features_by_usage_response import GetTopFeaturesByUsageResponse
_dynamic_imports: typing.Dict[str, str] = {
    "GetActivityParams": ".get_activity_params",
    "GetActivityResponse": ".get_activity_response",
    "GetEnvironmentFeatureUsageTimeSeriesParams": ".get_environment_feature_usage_time_series_params",
    "GetEnvironmentFeatureUsageTimeSeriesResponse": ".get_environment_feature_usage_time_series_response",
    "GetEnvironmentTraitUsageTimeSeriesParams": ".get_environment_trait_usage_time_series_params",
    "GetEnvironmentTraitUsageTimeSeriesResponse": ".get_environment_trait_usage_time_series_response",
    "GetPlanGrowthParams": ".get_plan_growth_params",
    "GetPlanGrowthResponse": ".get_plan_growth_response",
    "GetSummaryResponse": ".get_summary_response",
    "GetTopFeaturesByUsageParams": ".get_top_features_by_usage_params",
    "GetTopFeaturesByUsageResponse": ".get_top_features_by_usage_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GetActivityParams",
    "GetActivityResponse",
    "GetEnvironmentFeatureUsageTimeSeriesParams",
    "GetEnvironmentFeatureUsageTimeSeriesResponse",
    "GetEnvironmentTraitUsageTimeSeriesParams",
    "GetEnvironmentTraitUsageTimeSeriesResponse",
    "GetPlanGrowthParams",
    "GetPlanGrowthResponse",
    "GetSummaryResponse",
    "GetTopFeaturesByUsageParams",
    "GetTopFeaturesByUsageResponse",
]
