# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.time_series_granularity import TimeSeriesGranularity


class GetEnvironmentFeatureUsageTimeSeriesParams(UniversalBaseModel):
    """
    Input parameters
    """

    end_time: typing.Optional[dt.datetime] = None
    feature_id: typing.Optional[str] = None
    granularity: typing.Optional[TimeSeriesGranularity] = None
    start_time: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
