# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.company_matching_criteria import CompanyMatchingCriteria
from ..types.integration_state import IntegrationState
from ..types.integration_type import IntegrationType
from .raw_client import AsyncRawIntegrationsapiClient, RawIntegrationsapiClient
from .types.assume_stripe_installed_response import AssumeStripeInstalledResponse
from .types.claim_stripe_sandbox_keys_response import ClaimStripeSandboxKeysResponse
from .types.get_integration_webhook_url_response import GetIntegrationWebhookUrlResponse
from .types.get_stripe_sandbox_claim_link_response import GetStripeSandboxClaimLinkResponse
from .types.get_stripe_sandbox_keys_response import GetStripeSandboxKeysResponse
from .types.install_integration_response import InstallIntegrationResponse
from .types.install_stripe_claimable_sandbox_response import InstallStripeClaimableSandboxResponse
from .types.install_stripe_response import InstallStripeResponse
from .types.list_integrations_response import ListIntegrationsResponse
from .types.list_stripe_sandbox_countries_response import ListStripeSandboxCountriesResponse
from .types.load_sample_data_set_response import LoadSampleDataSetResponse
from .types.run_integration_response import RunIntegrationResponse
from .types.start_data_import_response import StartDataImportResponse
from .types.uninstall_integration_response import UninstallIntegrationResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class IntegrationsapiClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIntegrationsapiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIntegrationsapiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIntegrationsapiClient
        """
        return self._raw_client

    def run_integration(
        self, integration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RunIntegrationResponse:
        """
        Parameters
        ----------
        integration_id : str
            integration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RunIntegrationResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.run_integration(
            integration_id="integration_id",
        )
        """
        _response = self._raw_client.run_integration(integration_id, request_options=request_options)
        return _response.data

    def list_integrations(
        self,
        *,
        billing_only: typing.Optional[bool] = None,
        exclude_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        id: typing.Optional[str] = None,
        state: typing.Optional[IntegrationState] = None,
        type: typing.Optional[IntegrationType] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListIntegrationsResponse:
        """
        Parameters
        ----------
        billing_only : typing.Optional[bool]

        exclude_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        id : typing.Optional[str]

        state : typing.Optional[IntegrationState]

        type : typing.Optional[IntegrationType]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIntegrationsResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.list_integrations(
            billing_only=True,
            exclude_ids=["exclude_ids"],
            id="id",
            state="active",
            type="clerk",
            limit=1000000,
            offset=1000000,
        )
        """
        _response = self._raw_client.list_integrations(
            billing_only=billing_only,
            exclude_ids=exclude_ids,
            id=id,
            state=state,
            type=type,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    def get_integration_webhook_url(
        self, type: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIntegrationWebhookUrlResponse:
        """
        Parameters
        ----------
        type : str
            type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIntegrationWebhookUrlResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.get_integration_webhook_url(
            type="type",
        )
        """
        _response = self._raw_client.get_integration_webhook_url(type, request_options=request_options)
        return _response.data

    def install_integration(
        self,
        *,
        type: IntegrationType,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_sandbox: typing.Optional[bool] = OMIT,
        live_mode: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InstallIntegrationResponse:
        """
        Parameters
        ----------
        type : IntegrationType

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        config : typing.Optional[typing.Dict[str, typing.Any]]

        is_sandbox : typing.Optional[bool]

        live_mode : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstallIntegrationResponse
            Created

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.install_integration(
            type="clerk",
        )
        """
        _response = self._raw_client.install_integration(
            type=type,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            config=config,
            is_sandbox=is_sandbox,
            live_mode=live_mode,
            request_options=request_options,
        )
        return _response.data

    def start_data_import(
        self,
        *,
        integration_id: str,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartDataImportResponse:
        """
        Parameters
        ----------
        integration_id : str

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartDataImportResponse
            Created

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.start_data_import(
            integration_id="integration_id",
        )
        """
        _response = self._raw_client.start_data_import(
            integration_id=integration_id,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            request_options=request_options,
        )
        return _response.data

    def load_sample_data_set(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> LoadSampleDataSetResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadSampleDataSetResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.load_sample_data_set()
        """
        _response = self._raw_client.load_sample_data_set(request_options=request_options)
        return _response.data

    def get_stripe_sandbox_claim_link(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetStripeSandboxClaimLinkResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetStripeSandboxClaimLinkResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.get_stripe_sandbox_claim_link()
        """
        _response = self._raw_client.get_stripe_sandbox_claim_link(request_options=request_options)
        return _response.data

    def get_stripe_sandbox_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetStripeSandboxKeysResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetStripeSandboxKeysResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.get_stripe_sandbox_keys()
        """
        _response = self._raw_client.get_stripe_sandbox_keys(request_options=request_options)
        return _response.data

    def claim_stripe_sandbox_keys(
        self, *, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ClaimStripeSandboxKeysResponse:
        """
        Parameters
        ----------
        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ClaimStripeSandboxKeysResponse
            Created

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.claim_stripe_sandbox_keys(
            token="token",
        )
        """
        _response = self._raw_client.claim_stripe_sandbox_keys(token=token, request_options=request_options)
        return _response.data

    def assume_stripe_installed(
        self,
        *,
        type: IntegrationType,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_sandbox: typing.Optional[bool] = OMIT,
        live_mode: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AssumeStripeInstalledResponse:
        """
        Parameters
        ----------
        type : IntegrationType

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        config : typing.Optional[typing.Dict[str, typing.Any]]

        is_sandbox : typing.Optional[bool]

        live_mode : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AssumeStripeInstalledResponse
            Created

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.assume_stripe_installed(
            type="clerk",
        )
        """
        _response = self._raw_client.assume_stripe_installed(
            type=type,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            config=config,
            is_sandbox=is_sandbox,
            live_mode=live_mode,
            request_options=request_options,
        )
        return _response.data

    def install_stripe(
        self,
        *,
        type: IntegrationType,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_sandbox: typing.Optional[bool] = OMIT,
        live_mode: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InstallStripeResponse:
        """
        Parameters
        ----------
        type : IntegrationType

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        config : typing.Optional[typing.Dict[str, typing.Any]]

        is_sandbox : typing.Optional[bool]

        live_mode : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstallStripeResponse
            Created

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.install_stripe(
            type="clerk",
        )
        """
        _response = self._raw_client.install_stripe(
            type=type,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            config=config,
            is_sandbox=is_sandbox,
            live_mode=live_mode,
            request_options=request_options,
        )
        return _response.data

    def install_stripe_claimable_sandbox(
        self,
        *,
        email: str,
        country: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        seed_sample_data: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InstallStripeClaimableSandboxResponse:
        """
        Parameters
        ----------
        email : str

        country : typing.Optional[str]

        name : typing.Optional[str]

        seed_sample_data : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstallStripeClaimableSandboxResponse
            Created

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.install_stripe_claimable_sandbox(
            email="email",
        )
        """
        _response = self._raw_client.install_stripe_claimable_sandbox(
            email=email, country=country, name=name, seed_sample_data=seed_sample_data, request_options=request_options
        )
        return _response.data

    def list_stripe_sandbox_countries(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListStripeSandboxCountriesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListStripeSandboxCountriesResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.list_stripe_sandbox_countries()
        """
        _response = self._raw_client.list_stripe_sandbox_countries(request_options=request_options)
        return _response.data

    def uninstall_integration(
        self, integration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UninstallIntegrationResponse:
        """
        Parameters
        ----------
        integration_id : str
            integration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UninstallIntegrationResponse
            OK

        Examples
        --------
        from schematic import Schematic

        client = Schematic(
            api_key="YOUR_API_KEY",
        )
        client.integrationsapi.uninstall_integration(
            integration_id="integration_id",
        )
        """
        _response = self._raw_client.uninstall_integration(integration_id, request_options=request_options)
        return _response.data


class AsyncIntegrationsapiClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIntegrationsapiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIntegrationsapiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIntegrationsapiClient
        """
        return self._raw_client

    async def run_integration(
        self, integration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RunIntegrationResponse:
        """
        Parameters
        ----------
        integration_id : str
            integration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RunIntegrationResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.run_integration(
                integration_id="integration_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.run_integration(integration_id, request_options=request_options)
        return _response.data

    async def list_integrations(
        self,
        *,
        billing_only: typing.Optional[bool] = None,
        exclude_ids: typing.Optional[typing.Union[str, typing.Sequence[str]]] = None,
        id: typing.Optional[str] = None,
        state: typing.Optional[IntegrationState] = None,
        type: typing.Optional[IntegrationType] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListIntegrationsResponse:
        """
        Parameters
        ----------
        billing_only : typing.Optional[bool]

        exclude_ids : typing.Optional[typing.Union[str, typing.Sequence[str]]]

        id : typing.Optional[str]

        state : typing.Optional[IntegrationState]

        type : typing.Optional[IntegrationType]

        limit : typing.Optional[int]
            Page limit (default 100)

        offset : typing.Optional[int]
            Page offset (default 0)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListIntegrationsResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.list_integrations(
                billing_only=True,
                exclude_ids=["exclude_ids"],
                id="id",
                state="active",
                type="clerk",
                limit=1000000,
                offset=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_integrations(
            billing_only=billing_only,
            exclude_ids=exclude_ids,
            id=id,
            state=state,
            type=type,
            limit=limit,
            offset=offset,
            request_options=request_options,
        )
        return _response.data

    async def get_integration_webhook_url(
        self, type: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetIntegrationWebhookUrlResponse:
        """
        Parameters
        ----------
        type : str
            type

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetIntegrationWebhookUrlResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.get_integration_webhook_url(
                type="type",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_integration_webhook_url(type, request_options=request_options)
        return _response.data

    async def install_integration(
        self,
        *,
        type: IntegrationType,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_sandbox: typing.Optional[bool] = OMIT,
        live_mode: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InstallIntegrationResponse:
        """
        Parameters
        ----------
        type : IntegrationType

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        config : typing.Optional[typing.Dict[str, typing.Any]]

        is_sandbox : typing.Optional[bool]

        live_mode : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstallIntegrationResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.install_integration(
                type="clerk",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.install_integration(
            type=type,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            config=config,
            is_sandbox=is_sandbox,
            live_mode=live_mode,
            request_options=request_options,
        )
        return _response.data

    async def start_data_import(
        self,
        *,
        integration_id: str,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartDataImportResponse:
        """
        Parameters
        ----------
        integration_id : str

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartDataImportResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.start_data_import(
                integration_id="integration_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_data_import(
            integration_id=integration_id,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            request_options=request_options,
        )
        return _response.data

    async def load_sample_data_set(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> LoadSampleDataSetResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        LoadSampleDataSetResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.load_sample_data_set()


        asyncio.run(main())
        """
        _response = await self._raw_client.load_sample_data_set(request_options=request_options)
        return _response.data

    async def get_stripe_sandbox_claim_link(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetStripeSandboxClaimLinkResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetStripeSandboxClaimLinkResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.get_stripe_sandbox_claim_link()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_stripe_sandbox_claim_link(request_options=request_options)
        return _response.data

    async def get_stripe_sandbox_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetStripeSandboxKeysResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetStripeSandboxKeysResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.get_stripe_sandbox_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_stripe_sandbox_keys(request_options=request_options)
        return _response.data

    async def claim_stripe_sandbox_keys(
        self, *, token: str, request_options: typing.Optional[RequestOptions] = None
    ) -> ClaimStripeSandboxKeysResponse:
        """
        Parameters
        ----------
        token : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ClaimStripeSandboxKeysResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.claim_stripe_sandbox_keys(
                token="token",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.claim_stripe_sandbox_keys(token=token, request_options=request_options)
        return _response.data

    async def assume_stripe_installed(
        self,
        *,
        type: IntegrationType,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_sandbox: typing.Optional[bool] = OMIT,
        live_mode: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AssumeStripeInstalledResponse:
        """
        Parameters
        ----------
        type : IntegrationType

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        config : typing.Optional[typing.Dict[str, typing.Any]]

        is_sandbox : typing.Optional[bool]

        live_mode : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AssumeStripeInstalledResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.assume_stripe_installed(
                type="clerk",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.assume_stripe_installed(
            type=type,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            config=config,
            is_sandbox=is_sandbox,
            live_mode=live_mode,
            request_options=request_options,
        )
        return _response.data

    async def install_stripe(
        self,
        *,
        type: IntegrationType,
        company_matching_criteria: typing.Optional[CompanyMatchingCriteria] = OMIT,
        company_matching_field: typing.Optional[str] = OMIT,
        config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        is_sandbox: typing.Optional[bool] = OMIT,
        live_mode: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InstallStripeResponse:
        """
        Parameters
        ----------
        type : IntegrationType

        company_matching_criteria : typing.Optional[CompanyMatchingCriteria]

        company_matching_field : typing.Optional[str]

        config : typing.Optional[typing.Dict[str, typing.Any]]

        is_sandbox : typing.Optional[bool]

        live_mode : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstallStripeResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.install_stripe(
                type="clerk",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.install_stripe(
            type=type,
            company_matching_criteria=company_matching_criteria,
            company_matching_field=company_matching_field,
            config=config,
            is_sandbox=is_sandbox,
            live_mode=live_mode,
            request_options=request_options,
        )
        return _response.data

    async def install_stripe_claimable_sandbox(
        self,
        *,
        email: str,
        country: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        seed_sample_data: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InstallStripeClaimableSandboxResponse:
        """
        Parameters
        ----------
        email : str

        country : typing.Optional[str]

        name : typing.Optional[str]

        seed_sample_data : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InstallStripeClaimableSandboxResponse
            Created

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.install_stripe_claimable_sandbox(
                email="email",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.install_stripe_claimable_sandbox(
            email=email, country=country, name=name, seed_sample_data=seed_sample_data, request_options=request_options
        )
        return _response.data

    async def list_stripe_sandbox_countries(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListStripeSandboxCountriesResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListStripeSandboxCountriesResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.list_stripe_sandbox_countries()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_stripe_sandbox_countries(request_options=request_options)
        return _response.data

    async def uninstall_integration(
        self, integration_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> UninstallIntegrationResponse:
        """
        Parameters
        ----------
        integration_id : str
            integration_id

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UninstallIntegrationResponse
            OK

        Examples
        --------
        import asyncio

        from schematic import AsyncSchematic

        client = AsyncSchematic(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.integrationsapi.uninstall_integration(
                integration_id="integration_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.uninstall_integration(integration_id, request_options=request_options)
        return _response.data
